In [1]:
import pandas as pd
import numpy as np
from plotnine import *

%matplotlib inline

In [2]:
data = pd.read_csv("../../data/processed/expensas_full.csv",
                  dtype = {
                                "expensa_id": "object",
                                "unidad_id": "object",
                                "propietario_id": "object",
                                "inquilino_id": "object",
                                "consorcio_id": "object",
                                "consorcio_usa_fondo": "bool",
                                "consorcio_solo_muestra_cat": "bool",
                                "unidad_tipo":"object",
                                "expensa_concepto": "object",
                                "expensa_mes":"object",
                                "expensa_anio":"object",
                                "unidad_propietario":"object",
                                "unidad_inquilino":"object",
                                "expensa_version":"object"
                            },
                  parse_dates = ["consorcio_fecha_creacion", "expensa_primer_vencimiento", "expensa_segundo_vencimiento"])
data.pago_fecha = pd.to_datetime(data.pago_fecha, errors="coerce")
data.expensa_mes = data.expensa_mes.str.pad(width=2, side = "left", fillchar= "0")
data["expensa_fecha"] = pd.to_datetime(data.expensa_anio + "-" + data.expensa_mes + "-01")
data["expensa_mes_pago"] = pd.to_datetime(data.expensa_primer_vencimiento.dt.year.map(str) + '-'+ data.expensa_primer_vencimiento.dt.month.map(str) + '-01')
data.loc[data.pago_fecha.isna() | (data.pago_fecha >= (data.expensa_mes_pago + pd.DateOffset(months=1))), "target"] = 1
data.loc[data.target.isna(), "target"] = 0
data[["expensa_mes","expensa_anio", "expensa_mes_pago", "expensa_primer_vencimiento", "expensa_segundo_vencimiento", "pago_fecha", "pago_monto", "target"]]

,expensa_mes,expensa_anio,expensa_mes_pago,expensa_primer_vencimiento,expensa_segundo_vencimiento,pago_fecha,pago_monto,target
0,01,2014,2014-02-01,2014-02-10,2014-02-20,NaT,NaN,1.0
1,02,2014,2014-03-01,2014-03-10,2014-03-20,NaT,NaN,1.0
2,03,2014,2014-04-01,2014-04-10,2014-04-20,2014-04-08,624.45,0.0
3,04,2014,2014-05-01,2014-05-10,2014-05-20,2014-05-05,857.58,0.0
4,05,2014,2014-06-01,2014-06-10,2014-06-20,2014-06-04,710.80,0.0
5,06,2014,2014-07-01,2014-07-10,2014-07-20,2014-07-07,1109.25,0.0
6,07,2014,2014-08-01,2014-08-10,2014-08-20,2014-10-01,931.22,1.0
7,08,2014,2014-09-01,2014-09-10,2014-09-20,2014-09-09,879.12,0.0
8,09,2014,2014-10-01,2014-10-10,2014-10-20,2014-10-07,1538.82,0.0
9,10,2014,2014-11-01,2014-11-10,2014-11-20,2014-11-04,72.26,0.0
10,11,2014,2014-12-01,2014-12-10,2014-12-20,2014-12-03,845.17,0.0
11,12,2014,2015-01-01,2015-01-10,2015-01-20,2015-01-06,1045.08,0.0
12,01,2015,2015-02-01,2015-02-10,2015-02-20,2015-02-09,726.69,0.0
13,02,2015,2015-03-01,2015-03-10,2015-03-20,2015-03-03,1015.81,0.0
14,03,2015,2015-04-01,2015-04-10,2015-04-20,2015-04-07,752.75,0.0
15,04,2015,2015-05-01,2015-05-10,2015-05-20,2015-05-04,879.43,0.0
16,05,2015,2015-06-01,2015-06-10,2015-06-20,2015-06-08,730.04,0.0
17,06,2015,2015-07-01,2015-07-10,2015-07-20,2015-07-06,1061.82,0.0
18,07,2015,2015-08-01,2015-08-10,2015-08-20,2015-08-04,821.27,0.0
19,08,2015,2015-09-01,2015-09-10,2015-09-20,2015-09-01,937.71,0.0
20,09,2015,2015-10-01,2015-10-10,2015-10-20,2015-10-05,1109.71,0.0
21,10,2015,2015-11-01,2015-11-10,2015-11-20,2015-11-02,1046.19,0.0
22,11,2015,2015-12-01,2015-12-10,2015-12-20,2015-12-14,1181.26,0.0
23,12,2015,2016-01-01,2016-01-10,2016-01-20,2016-01-04,1035.76,0.0
24,01,2016,2016-02-01,2016-02-10,2016-02-20,2016-02-10,1012.04,0.0
25,02,2016,2016-03-01,2016-03-10,2016-03-20,2016-03-04,1075.03,0.0
26,03,2016,2016-04-01,2016-04-10,2016-04-20,2016-04-04,744.00,0.0
27,04,2016,2016-05-01,2016-05-10,2016-05-20,2016-05-10,1290.00,0.0
28,05,2016,2016-06-01,2016-06-10,2016-06-20,2016-06-07,1054.00,0.0
29,06,2016,2016-07-01,2016-07-10,2016-07-20,2016-07-05,2314.00,0.0
...,...,...,...,...,...,...,...,...
229965,12,2018,2019-01-01,2019-01-12,2019-01-21,NaT,NaN,1.0
229966,11,2018,2018-12-01,2018-12-12,2018-12-21,NaT,NaN,1.0
229967,12,2018,2019-01-01,2019-01-12,2019-01-21,NaT,NaN,1.0
229968,11,2018,2018-12-01,2018-12-12,2018-12-21,NaT,NaN,1.0
229969,12,2018,2019-01-01,2019-01-12,2019-01-21,NaT,NaN,1.0
229970,12,2018,2019-01-01,2019-01-31,2019-01-31,NaT,NaN,1.0
229971,12,2018,2019-01-01,2019-01-31,2019-01-31,2019-02-11,3709.00,1.0
229972,12,2018,2019-01-01,2019-01-31,2019-01-31,2019-02-11,10.00,1.0
229973,12,2018,2019-01-01,2019-01-15,2019-01-24,2019-01-15,3678.00,0.0
229974,12,2018,2019-01-01,2019-01-31,2019-01-31,2019-02-11,75.00,1.0
229975,12,2018,2019-01-01,2019-01-31,2019-01-31,2019-02-11,1.00,1.0
229976,12,2018,2019-01-01,2019-01-31,2019-01-31,2019-02-11,74.00,1.0
229977,12,2018,2019-01-01,2019-01-15,2019-01-24,2019-01-25,2568.00,0.0
229978,12,2018,2019-01-01,2019-01-31,2019-01-31,NaT,NaN,1.0
229979,12,2018,2019-01-01,2019-01-31,2019-01-31,2019-02-11,74.00,1.0
229980,12,2018,2019-01-01,2019-01-15,2019-01-24,2019-01-15,3760.00,0.0
229981,12,2018,2019-01-01,2019-01-15,2019-01-24,2019-01-15,3672.00,0.0
229982,12,2018,2019-01-01,2019-01-15,2019-01-24,2019-01-21,3835.00,0.0
229983,12,2018,2019-01-01,2019-01-15,2019-01-24,2019-01-22,507.00,0.0
229984,12,2018,2019-01-01,2019-01-31,2019-01-31,2019-02-11,109.00,1.0
229985,12,2018,2019-01-01,2019-01-31,2019-01-31,2019-02-11,1.00,1.0
229986,12,2018,2019-01-01,2019-01-31,2019-01-31,2019-02-11,75.00,1.0
229987,12,2018,2019-01-01,2019-01-15,2019-01-24,2019-01-15,3678.00,0.0
229988,12,2018,2019-01-01,2019-01-15,2019-01-24,2019-01-15,497.00,0.0
229989,12,2018,2019-01-01,2019-01-31,2019-01-31,2019-02-11,217.00,1.0
229990,12,2018,2019-01-01,2019-01-31,2019-01-31,2019-02-11,10.00,1.0
229991,12,2018,2019-01-01,2019-01-31,2019-01-31,2019-02-11,10.00,1.0
229992,12,2018,2019-01-01,2019-01-31,2019-01-31,2019-02-11,5.00,1.0
229993,12,2018,2019-01-01,2019-01-31,2019-01-31,2019-02-11,5.00,1.0
229994,12,2018,2019-01-01,2019-01-15,2019-01-20,2019-03-08,7184.00,1.0

In [3]:
data.columns

Index(['consorcio_id', 'consorcio_fecha_creacion', 'consorcio_nombre',
       'consorcio_modo_pago', 'consorcio_visibilidad_gasto', 'consorcio_tipo',
       'consorcio_usa_fondo', 'consorcio_solo_muestra_cat', 'unidad_id',
       'unidad_denominacion', 'unidad_metros', 'unidad_tipo',
       'unidad_propietario', 'expensa_id', 'unidad_inquilino',
       'expensa_primer_vencimiento', 'expensa_segundo_vencimiento',
       'expensa_monto', 'expensa_monto_total', 'expensa_monto_parcial',
       'expensa_proporcion', 'expensa_interes_primer_vencimiento',
       'expensa_ineteres_segundo_vencimiento', 'expensa_mes', 'expensa_anio',
       'expensa_version', 'expensa_concepto', 'pago_fecha', 'pago_monto',
       'pago_metodo', 'expensa_fecha', 'expensa_mes_pago', 'target'],
      dtype='object')

In [33]:
df = data[['consorcio_id', 'consorcio_nombre', 'unidad_id',
       'unidad_denominacion','unidad_tipo','expensa_id',
       'expensa_proporcion', 'expensa_mes', 'expensa_fecha', 'expensa_mes_pago', 
       'expensa_version', 'expensa_concepto', 'pago_fecha', 'pago_metodo','target']]

In [34]:
df["expensa_mes_pago_anterior"] = df.expensa_mes_pago - pd.DateOffset(months=1)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [35]:
df.loc[df.pago_metodo.isna(), "pago_metodo"] = "Impago"

C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [36]:
df[["consorcio_id","unidad_id", "expensa_fecha","expensa_mes_pago","expensa_mes_pago_anterior"]]

,consorcio_id,unidad_id,expensa_fecha,expensa_mes_pago,expensa_mes_pago_anterior
0,8,3,2014-01-01,2014-02-01,2014-01-01
1,8,3,2014-02-01,2014-03-01,2014-02-01
2,8,3,2014-03-01,2014-04-01,2014-03-01
3,8,3,2014-04-01,2014-05-01,2014-04-01
4,8,3,2014-05-01,2014-06-01,2014-05-01
5,8,3,2014-06-01,2014-07-01,2014-06-01
6,8,3,2014-07-01,2014-08-01,2014-07-01
7,8,3,2014-08-01,2014-09-01,2014-08-01
8,8,3,2014-09-01,2014-10-01,2014-09-01
9,8,3,2014-10-01,2014-11-01,2014-10-01
10,8,3,2014-11-01,2014-12-01,2014-11-01
11,8,3,2014-12-01,2015-01-01,2014-12-01
12,8,3,2015-01-01,2015-02-01,2015-01-01
13,8,3,2015-02-01,2015-03-01,2015-02-01
14,8,3,2015-03-01,2015-04-01,2015-03-01
15,8,3,2015-04-01,2015-05-01,2015-04-01
16,8,3,2015-05-01,2015-06-01,2015-05-01
17,8,3,2015-06-01,2015-07-01,2015-06-01
18,8,3,2015-07-01,2015-08-01,2015-07-01
19,8,3,2015-08-01,2015-09-01,2015-08-01
20,8,3,2015-09-01,2015-10-01,2015-09-01
21,8,3,2015-10-01,2015-11-01,2015-10-01
22,8,3,2015-11-01,2015-12-01,2015-11-01
23,8,3,2015-12-01,2016-01-01,2015-12-01
24,8,3,2016-01-01,2016-02-01,2016-01-01
25,8,3,2016-02-01,2016-03-01,2016-02-01
26,8,3,2016-03-01,2016-04-01,2016-03-01
27,8,3,2016-04-01,2016-05-01,2016-04-01
28,8,3,2016-05-01,2016-06-01,2016-05-01
29,8,3,2016-06-01,2016-07-01,2016-06-01
...,...,...,...,...,...
229965,2033,47114,2018-12-01,2019-01-01,2018-12-01
229966,2033,47115,2018-11-01,2018-12-01,2018-11-01
229967,2033,47115,2018-12-01,2019-01-01,2018-12-01
229968,2033,47116,2018-11-01,2018-12-01,2018-11-01
229969,2033,47116,2018-12-01,2019-01-01,2018-12-01
229970,2035,47154,2018-12-01,2019-01-01,2018-12-01
229971,2035,47155,2018-12-01,2019-01-01,2018-12-01
229972,2035,47156,2018-12-01,2019-01-01,2018-12-01
229973,2035,47157,2018-12-01,2019-01-01,2018-12-01
229974,2035,47158,2018-12-01,2019-01-01,2018-12-01
229975,2035,47159,2018-12-01,2019-01-01,2018-12-01
229976,2035,47160,2018-12-01,2019-01-01,2018-12-01
229977,2035,47161,2018-12-01,2019-01-01,2018-12-01
229978,2035,47162,2018-12-01,2019-01-01,2018-12-01
229979,2035,47163,2018-12-01,2019-01-01,2018-12-01
229980,2035,47164,2018-12-01,2019-01-01,2018-12-01
229981,2035,47165,2018-12-01,2019-01-01,2018-12-01
229982,2035,47166,2018-12-01,2019-01-01,2018-12-01
229983,2035,47167,2018-12-01,2019-01-01,2018-12-01
229984,2035,47168,2018-12-01,2019-01-01,2018-12-01
229985,2035,47169,2018-12-01,2019-01-01,2018-12-01
229986,2035,47170,2018-12-01,2019-01-01,2018-12-01
229987,2035,47171,2018-12-01,2019-01-01,2018-12-01
229988,2035,47172,2018-12-01,2019-01-01,2018-12-01
229989,2035,47173,2018-12-01,2019-01-01,2018-12-01
229990,2035,47174,2018-12-01,2019-01-01,2018-12-01
229991,2035,47175,2018-12-01,2019-01-01,2018-12-01
229992,2035,47176,2018-12-01,2019-01-01,2018-12-01
229993,2035,47177,2018-12-01,2019-01-01,2018-12-01
229994,2055,47610,2018-12-01,2019-01-01,2018-12-01

In [37]:
df.loc[df.consorcio_id == "11", :]

,consorcio_id,consorcio_nombre,unidad_id,unidad_denominacion,unidad_tipo,expensa_id,expensa_proporcion,expensa_mes,expensa_fecha,expensa_mes_pago,expensa_version,expensa_concepto,pago_fecha,pago_metodo,target,expensa_mes_pago_anterior
4164,11,Metropolis,135,2 (B),Departamento,2588,2.400533,05,2014-05-01,2014-06-01,1,1,2014-10-23,Efectivo,1.0,2014-05-01
4165,11,Metropolis,135,2 (B),Departamento,3372,3.223249,07,2014-07-01,2014-08-01,1,1,2014-10-23,Efectivo,1.0,2014-07-01
4166,11,Metropolis,135,2 (B),Departamento,7643,2.073637,10,2014-10-01,2014-11-01,1,1,2014-11-07,Rapipago,0.0,2014-10-01
4167,11,Metropolis,135,2 (B),Departamento,8880,2.099234,11,2014-11-01,2014-12-01,1,1,2014-12-10,Rapipago,0.0,2014-11-01
4168,11,Metropolis,135,2 (B),Departamento,12923,2.139494,12,2014-12-01,2015-01-01,1,1,2015-01-09,Rapipago,0.0,2014-12-01
4169,11,Metropolis,135,2 (B),Departamento,14658,2.120404,01,2015-01-01,2015-02-01,1,1,2015-02-09,Rapipago,0.0,2015-01-01
4170,11,Metropolis,135,2 (B),Departamento,16270,2.117749,02,2015-02-01,2015-03-01,1,1,2015-03-11,Rapipago,0.0,2015-02-01
4171,11,Metropolis,135,2 (B),Departamento,18947,2.123804,03,2015-03-01,2015-04-01,1,1,2015-05-22,Rapipago,1.0,2015-03-01
4172,11,Metropolis,135,2 (B),Departamento,20472,2.109472,04,2015-04-01,2015-05-01,1,1,2015-05-22,Rapipago,0.0,2015-04-01
4173,11,Metropolis,135,2 (B),Departamento,22581,2.133452,05,2015-05-01,2015-06-01,1,1,2015-06-09,Rapipago,0.0,2015-05-01
4174,11,Metropolis,135,2 (B),Departamento,24330,2.127065,06,2015-06-01,2015-07-01,1,1,2015-07-23,Rapipago,0.0,2015-06-01
4175,11,Metropolis,135,2 (B),Departamento,26939,2.125503,07,2015-07-01,2015-08-01,1,1,2015-08-11,Pago Facil,0.0,2015-07-01
4176,11,Metropolis,135,2 (B),Departamento,28559,2.117996,08,2015-08-01,2015-09-01,1,1,2015-09-09,Rapipago,0.0,2015-08-01
4177,11,Metropolis,135,2 (B),Departamento,30491,2.152311,09,2015-09-01,2015-10-01,1,1,2015-10-09,Pago Facil,0.0,2015-09-01
4178,11,Metropolis,135,2 (B),Departamento,32787,2.146364,10,2015-10-01,2015-11-01,1,1,2015-11-10,Pago Facil,0.0,2015-10-01
4179,11,Metropolis,135,2 (B),Departamento,34729,2.354368,11,2015-11-01,2015-12-01,1,1,2015-12-10,Rapipago,0.0,2015-11-01
4180,11,Metropolis,135,2 (B),Departamento,36392,2.376532,12,2015-12-01,2016-01-01,1,1,2016-01-12,Pago Facil,0.0,2015-12-01
4181,11,Metropolis,135,2 (B),Departamento,40266,2.125429,01,2016-01-01,2016-02-01,1,1,2016-02-12,Pago Facil,0.0,2016-01-01
4182,11,Metropolis,135,2 (B),Departamento,44150,2.322374,02,2016-02-01,2016-03-01,1,1,2016-03-10,Pago Facil,0.0,2016-02-01
4183,11,Metropolis,135,2 (B),Departamento,47652,2.091524,03,2016-03-01,2016-04-01,1,1,2016-04-08,Pago Facil,0.0,2016-03-01
4184,11,Metropolis,135,2 (B),Departamento,49777,2.122124,04,2016-04-01,2016-05-01,1,1,2016-05-10,Pago Facil,0.0,2016-04-01
4185,11,Metropolis,135,2 (B),Departamento,54456,2.077615,05,2016-05-01,2016-06-01,1,1,2016-06-10,Rapipago,0.0,2016-05-01
4186,11,Metropolis,135,2 (B),Departamento,59223,2.103003,06,2016-06-01,2016-07-01,1,1,2016-09-13,Pago Facil,1.0,2016-06-01
4187,11,Metropolis,135,2 (B),Departamento,62588,2.300964,07,2016-07-01,2016-08-01,1,1,2016-08-10,Pago Facil,0.0,2016-07-01
4188,11,Metropolis,135,2 (B),Departamento,69680,1.627400,08,2016-08-01,2016-09-01,1,1,2016-09-09,Rapipago,0.0,2016-08-01
4189,11,Metropolis,135,2 (B),Departamento,74206,2.079806,09,2016-09-01,2016-10-01,1,1,2016-10-07,Pago Facil,0.0,2016-09-01
4190,11,Metropolis,135,2 (B),Departamento,79677,2.034085,10,2016-10-01,2016-11-01,1,1,2016-11-14,Pago Facil,0.0,2016-10-01
4191,11,Metropolis,135,2 (B),Departamento,84290,2.280392,11,2016-11-01,2016-12-01,1,1,2016-12-05,Pago Facil,0.0,2016-11-01
4192,11,Metropolis,135,2 (B),Departamento,89224,2.112542,12,2016-12-01,2017-01-01,1,1,2017-01-06,Pago Facil,0.0,2016-12-01
4193,11,Metropolis,135,2 (B),Departamento,95920,2.259772,01,2017-01-01,2017-02-01,1,1,2017-02-10,Pago Facil,0.0,2017-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6727,11,Metropolis,11462,Cochera nº69,Cochera,12999,0.293074,12,2014-12-01,2015-01-01,1,1,2015-01-06,Rapipago,0.0,2014-12-01
6728,11,Metropolis,11462,Cochera nº69,Cochera,14734,0.329104,01,2015-01-01,2015-02-01,1,1,2015-02-10,Rapipago,0.0,2015-01-01
6729,11,Metropolis,11462,Cochera nº69,Cochera,16346,0.292681,02,2015-02-01,2015-03-01,1,1,2015-03-09,Rapipago,0.0,2015-02-01
6730,11,Metropolis,11462,Cochera nº69,Cochera,19037,0.292764,03,2015-03-01,2015-04-01,1,1,2015-04-08,Rapipago,0.0,2015-03-01
6731,11,Metropolis,11462,Cochera nº69,Cochera,20548,0.292710,04,2015-04-01,2015-05-01,1,1,2015-05-06,Rapipago,0.0,2015-04-01
6732,11,Metropolis,11462,Cochera nº69,Cochera,22657,0.292836,05,2015-05-01,2015-06-01,1,1,2015-06-15,Rapipago,0.0,2015-05-01
6733,11,Metropolis,11462,Cochera nº69,Cochera,24406,0.292901,06,2015-06-01,2015-07-01,1,1,2015-07-07,Rapipago,0.0,2015-06-01
6734,11,Metropolis,11462,Cochera nº69,Cochera,27015,0.292893,07,2015-07-01,2015-08-01,1,1,2015-08-06,Rapipago,0.0,2015-07-01
6735,11,Metropolis,11462,Cochera nº69,Cochera,28635,0.292806,08,2015-08-01,2015-09-01,1,1,2015-09-02,Pago Facil,0.0,2015-08-01
6736,11,Metropolis,11462,Cochera nº69,Cochera,30567,0.292832,09,2015-09-01,2015-10-01,1,1,2015-10-07,Pago Facil,0.0,2015-09-01
6737,11,Metropolis,11462,Cochera nº69,Cochera,32863,0.292742,10,2015-10-01,2015-11-01,1,1,2015-11-05,Pago Facil,0.0,2015-10-01
6738,11,Metropolis,11462,Cochera nº69,Cochera,34805,0.345306,11,2015-11-01,2015-12-01,1,1,2015-12-10,Pago Facil,0.0,2015-11-01
6739,11,Metropolis,11462,Cochera nº69,Cochera,36468,0.292897,12,2015-12-01,2016-01-01,1,1,2016-01-05,Rapipago,0.0,2015-12-01
6740,11,Metropolis,11462,Cochera nº69,Cochera,40342,0.292885,01,2016-01-01,2016-02-01,1,1,2016-02-11,Rapipago,0.0,2016-01-01
6741,11,Metropolis,11462,Cochera nº69,Cochera,44226,0.227715,02,2016-02-01,2016-03-01,1,1,2016-03-08,Pago Facil,0.0,2016-02-01
6742,11,Metropolis,11462,Cochera nº69,Cochera,47728,0.253877,03,2016-03-01,2016-04-01,1,1,2016-04-08,Rapipago,0.0,2016-03-01
6743,11,Metropolis,11462,Cochera nº69,Cochera,49853,0.225625,04,2016-04-01,2016-05-01,1,1,2016-05-05,Rapipago,0.0,2016-04-01
6744,11,Metropolis,11462,Cochera nº69,Cochera,54532,0.257288,05,2016-05-01,2016-06-01,1,1,2016-06-06,Rapipago,0.0,2016-05-01
6745,11,Metropolis,11462,Cochera nº69,Cochera,59299,0.250619,06,2016-06-01,2016-07-01,1,1,2016-07-05,Rapipago,0.0,2016-06-01
6746,11,Metropolis,11462,Cochera nº69,Cochera,62664,0.290735,07,2016-07-01,2016-08-01,1,1,2016-08-03,Rapipago,0.0,2016-07-01
6747,11,Metropolis,11462,Cochera nº69,Cochera,69756,0.276730,08,2016-08-01,2016-09-01,1,1,2016-09-06,Rapipago,0.0,2016-08-01
6748,11,Metropolis,11462,Cochera nº69,Cochera,74282,0.266614,09,2016-09-01,2016-10-01,1,1,2016-10-04,Rapipago,0.0,2016-09-01
6749,11,Metropolis,11462,Cochera nº69,Cochera,79753,0.318014,10,2016-10-01,2016-11-01,1,1,2016-11-07,Rapipago,0.0,2016-10-01
6750,11,Metropolis,11462,Cochera nº69,Cochera,84366,0.256772,11,2016-11-01,2016-12-01,1,1,2016-12-07,Rapipago,0.0,2016-11-01
6751,11,Metropolis,11462,Cochera nº69,Cochera,89300,0.256398,12,2016-12-01,2017-01-01,1,1,2017-01-09,Rapipago,0.0,2016-12-01
6752,11,Metropolis,11462,Cochera nº69,Cochera,95996,0.213355,01,2017-01-01,2017-02-01,1,1,2017-02-15,Rapipago,0.0,2017-01-01
6753,11,Metropolis,11462,Cochera nº69,Cochera,98412,0.260215,02,2017-02-01,2017-03-01,1,1,2017-03-08,Rapipago,0.0,2017-02-01
6754,11,Metropolis,11462,Cochera nº69,Cochera,104458,0.245660,03,2017-03-01,2017-04-01,1,1,2017-04-06,Pago Facil,0.0,2017-03-01
6755,11,Metropolis,11462,Cochera nº69,Cochera,109925,0.266102,04,2017-04-01,2017-05-01,1,1,2017-05-11,Rapipago,0.0,2017-04-01
6756,11,Metropolis,11462,Cochera nº69,Cochera,117524,0.269641,05,2017-05-01,2017-06-01,1,1,2017-06-08,Pago Facil,0.0,2017-05-01

In [38]:
estadisticas_consorcio = df[["consorcio_id", "expensa_mes_pago", "target", "expensa_id", "pago_metodo"]]

In [10]:
estadisticas_consorcio["pago_metodo_2"] = estadisticas_consorcio.pago_metodo
estadisticas_consorcio.loc[estadisticas_consorcio.target==1, "pago_metodo_2"] = "Impago"
estadisticas_consorcio["efectivo"] = estadisticas_consorcio.pago_metodo_2 == "Efectivo"

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [11]:
impagos_por_mes = estadisticas_consorcio[["consorcio_id","expensa_mes_pago","target"]].groupby(["consorcio_id","expensa_mes_pago"]).sum()
total_pagos_por_mes =  estadisticas_consorcio[["consorcio_id","expensa_mes_pago","expensa_id"]].groupby(["consorcio_id","expensa_mes_pago"]).count()
pagos_efectivos_por_mes = estadisticas_consorcio[["consorcio_id","expensa_mes_pago","efectivo"]].groupby(["consorcio_id","expensa_mes_pago"]).sum()

In [119]:
resumen_consorcios = pd.merge(impagos_por_mes, total_pagos_por_mes, left_index=True, right_index=True)
resumen_consorcios = pd.merge(resumen_consorcios, pagos_efectivos_por_mes, left_index=True, right_index=True)
resumen_consorcios.columns = ["impagos", "cantidad_expensas", "cantidad_efectivo"]
resumen_consorcios["prop_impagos"] = resumen_consorcios.impagos / resumen_consorcios.cantidad_expensas
resumen_consorcios["prop_efectivo"] = resumen_consorcios.cantidad_efectivo / resumen_consorcios.cantidad_expensas
#resumen_consorcios = resumen_consorcios[["cantidad_expensas","prop_impagos", "prop_efectivo"]]
resumen_consorcios.to_csv("../../data/processed/resumen_consorcios.csv")

In [118]:
resumen_consorcios

                               impagos  cantidad_expensas  cantidad_efectivo  \
consorcio_id expensa_mes_pago
11           2014-06-01           64.0                 65                1.0
             2014-08-01           64.0                 65                1.0
             2014-11-01           13.0                 77               24.0
             2014-12-01            9.0                 77                6.0
             2015-01-01           12.0                 77                1.0
             2015-02-01            8.0                 77                0.0
             2015-03-01           11.0                 77                0.0
             2015-04-01           10.0                 77                1.0
             2015-05-01            8.0                 77                0.0
             2015-06-01           12.0                 77                0.0
             2015-07-01            8.0                 77                0.0
             2015-08-01            3.0                 77                0.0
             2015-09-01            6.0                 77                0.0
             2015-10-01            5.0                 77                0.0
             2015-11-01            7.0                 77                0.0
             2015-12-01            7.0                 77                0.0
             2016-01-01            5.0                 77                0.0
             2016-02-01            9.0                 77                0.0
             2016-03-01            7.0                 77                0.0
             2016-04-01            5.0                 77                0.0
             2016-05-01            8.0                 77                0.0
             2016-06-01            6.0                 77                0.0
             2016-07-01            7.0                 77                0.0
             2016-08-01            6.0                 77                0.0
             2016-09-01            4.0                 76                0.0
             2016-10-01            3.0                 77                0.0
             2016-11-01            3.0                 77                0.0
             2016-12-01            6.0                 77                0.0
             2017-01-01            3.0                 77                0.0
             2017-02-01            8.0                 77                0.0
...                                ...                ...                ...
9            2016-08-01            2.0                 27                0.0
             2016-09-01            4.0                 28                0.0
             2016-10-01            3.0                 28                0.0
             2016-11-01            2.0                 28                0.0
             2016-12-01            2.0                 28                0.0
             2017-01-01            3.0                 28                0.0
             2017-02-01            4.0                 28                0.0
             2017-03-01            3.0                 29                0.0
             2017-04-01            2.0                 28                1.0
             2017-05-01            4.0                 27                0.0
             2017-06-01            1.0                 28                0.0
             2017-07-01            1.0                 28                0.0
             2017-08-01            2.0                 28                0.0
             2017-09-01            3.0                 28                0.0
             2017-10-01            3.0                 28                0.0
             2017-11-01            1.0                 28                0.0
             2017-12-01            3.0                 28                0.0
             2018-01-01            3.0                 28                0.0
             2018-02-01            6.0                 28                0.0
             2018-03-01            1.0                 28                0.0
             2018-04-01            1.0                 28                0.0
             2018-05-01            3.0                 28                0.0
             2018-06-01            4.0                 28                0.0
             2018-07-01            5.0                 28                0.0
             2018-08-01            5.0                 28                0.0
             2018-09-01            1.0                 28                0.0
             2018-10-01            4.0                 28                0.0
             2018-11-01            3.0                 28                0.0
             2018-12-01            1.0                 28                0.0
             2019-01-01            1.0                 28                0.0

                               prop_impagos  prop_efectivo
consorcio_id expensa_mes_pago
11           2014-06-01            0.984615       0.015385
             2014-08-01            0.984615       0.015385
             2014-11-01            0.168831       0.311688
             2014-12-01            0.116883       0.077922
             2015-01-01            0.155844       0.012987
             2015-02-01            0.103896       0.000000
             2015-03-01            0.142857       0.000000
             2015-04-01            0.129870       0.012987
             2015-05-01            0.103896       0.000000
             2015-06-01            0.155844       0.000000
             2015-07-01            0.103896       0.000000
             2015-08-01            0.038961       0.000000
             2015-09-01            0.077922       0.000000
             2015-10-01            0.064935       0.000000
             2015-11-01            0.090909       0.000000
             2015-12-01            0.090909       0.000000
             2016-01-01            0.064935       0.000000
             2016-02-01            0.116883       0.000000
             2016-03-01            0.090909       0.000000
             2016-04-01            0.064935       0.000000
             2016-05-01            0.103896       0.000000
             2016-06-01            0.077922       0.000000
             2016-07-01            0.090909       0.000000
             2016-08-01            0.077922       0.000000
             2016-09-01            0.052632       0.000000
             2016-10-01            0.038961       0.000000
             2016-11-01            0.038961       0.000000
             2016-12-01            0.077922       0.000000
             2017-01-01            0.038961       0.000000
             2017-02-01            0.103896       0.000000
...                                     ...            ...
9            2016-08-01            0.074074       0.000000
             2016-09-01            0.142857       0.000000
             2016-10-01            0.107143       0.000000
             2016-11-01            0.071429       0.000000
             2016-12-01            0.071429       0.000000
             2017-01-01            0.107143       0.000000
             2017-02-01            0.142857       0.000000
             2017-03-01            0.103448       0.000000
             2017-04-01            0.071429       0.035714
             2017-05-01            0.148148       0.000000
             2017-06-01            0.035714       0.000000
             2017-07-01            0.035714       0.000000
             2017-08-01            0.071429       0.000000
             2017-09-01            0.107143       0.000000
             2017-10-01            0.107143       0.000000
             2017-11-01            0.035714       0.000000
             2017-12-01            0.107143       0.000000
             2018-01-01            0.107143       0.000000
             2018-02-01            0.214286       0.000000
             2018-03-01            0.035714       0.000000
             2018-04-01            0.035714       0.000000
             2018-05-01            0.107143       0.000000
             2018-06-01            0.142857       0.000000
             2018-07-01            0.178571       0.000000
             2018-08-01            0.178571       0.000000
             2018-09-01            0.035714       0.000000
             2018-10-01            0.142857       0.000000
             2018-11-01            0.107143       0.000000
             2018-12-01            0.035714       0.000000
             2019-01-01            0.035714       0.000000

[5010 rows x 5 columns]

In [13]:
def get_cum_by_unidad(unidad_id):
    data_unidad = df.loc[data.unidad_id == unidad_id, ["unidad_id","expensa_mes_pago", "target"]].sort_values("expensa_mes_pago")
    data_unidad["cum_impagos"] = data_unidad.target.cumsum()
    data_unidad["total_pagos"] = range(1,data_unidad.shape[0] + 1)
    data_unidad["prop_impagos"] = data_unidad.cum_impagos / data_unidad.total_pagos    
    return data_unidad[["unidad_id","expensa_mes_pago","prop_impagos"]]

In [14]:
get_cum_by_unidad("10")

    unidad_id expensa_mes_pago  prop_impagos
420        10       2014-02-01      1.000000
421        10       2014-03-01      1.000000
422        10       2014-04-01      0.666667
423        10       2014-05-01      0.500000
424        10       2014-06-01      0.400000
425        10       2014-07-01      0.500000
426        10       2014-08-01      0.428571
427        10       2014-09-01      0.375000
428        10       2014-10-01      0.333333
429        10       2014-11-01      0.300000
430        10       2014-12-01      0.272727
431        10       2015-01-01      0.250000
432        10       2015-02-01      0.230769
433        10       2015-03-01      0.214286
434        10       2015-04-01      0.200000
435        10       2015-05-01      0.187500
436        10       2015-06-01      0.176471
437        10       2015-07-01      0.166667
438        10       2015-08-01      0.157895
439        10       2015-09-01      0.150000
440        10       2015-10-01      0.142857
441        10       2015-11-01      0.136364
442        10       2015-12-01      0.130435
443        10       2016-01-01      0.125000
444        10       2016-02-01      0.120000
445        10       2016-03-01      0.115385
446        10       2016-04-01      0.111111
447        10       2016-05-01      0.107143
448        10       2016-06-01      0.103448
449        10       2016-07-01      0.100000
450        10       2016-08-01      0.096774
451        10       2016-09-01      0.093750
452        10       2016-10-01      0.090909
453        10       2016-11-01      0.088235
454        10       2016-12-01      0.085714
455        10       2017-01-01      0.083333
456        10       2017-02-01      0.081081
457        10       2017-03-01      0.105263
458        10       2017-04-01      0.102564
459        10       2017-05-01      0.100000
460        10       2017-06-01      0.097561
461        10       2017-07-01      0.095238
462        10       2017-08-01      0.093023
463        10       2017-09-01      0.090909
464        10       2017-10-01      0.088889
465        10       2017-11-01      0.086957
466        10       2017-12-01      0.085106
467        10       2018-01-01      0.083333
468        10       2018-02-01      0.081633
469        10       2018-03-01      0.080000
470        10       2018-04-01      0.078431
471        10       2018-05-01      0.076923
472        10       2018-06-01      0.075472
473        10       2018-07-01      0.074074
474        10       2018-08-01      0.072727
475        10       2018-09-01      0.071429
476        10       2018-10-01      0.070175
477        10       2018-11-01      0.068966
478        10       2018-12-01      0.067797
479        10       2019-01-01      0.066667

In [15]:
dfs = list()
for unidad in df.unidad_id.unique():
    data_unidad = get_cum_by_unidad(unidad)
    dfs.append(data_unidad)

In [19]:
resumen_unidades = pd.concat(dfs)

In [75]:
resumen_unidades.to_csv("../../data/processed/resumen_unidades.csv", index=False)

In [28]:
resumen_unidades = pd.read_csv("../../data/processed/resumen_unidades.csv", 
                               dtype = {
                                   "unidad_id":"object"
                               },
                               parse_dates=["expensa_mes_pago"])

In [29]:
resumen_unidades

       unidad_id expensa_mes_pago  prop_impagos
0              3       2014-02-01      1.000000
1              3       2014-03-01      1.000000
2              3       2014-04-01      0.666667
3              3       2014-05-01      0.500000
4              3       2014-06-01      0.400000
5              3       2014-07-01      0.333333
6              3       2014-08-01      0.428571
7              3       2014-09-01      0.375000
8              3       2014-10-01      0.333333
9              3       2014-11-01      0.300000
10             3       2014-12-01      0.272727
11             3       2015-01-01      0.250000
12             3       2015-02-01      0.230769
13             3       2015-03-01      0.214286
14             3       2015-04-01      0.200000
15             3       2015-05-01      0.187500
16             3       2015-06-01      0.176471
17             3       2015-07-01      0.166667
18             3       2015-08-01      0.157895
19             3       2015-09-01      0.150000
20             3       2015-10-01      0.142857
21             3       2015-11-01      0.136364
22             3       2015-12-01      0.130435
23             3       2016-01-01      0.125000
24             3       2016-02-01      0.120000
25             3       2016-03-01      0.115385
26             3       2016-04-01      0.111111
27             3       2016-05-01      0.107143
28             3       2016-06-01      0.103448
29             3       2016-07-01      0.100000
...          ...              ...           ...
229965     47114       2019-01-01      1.000000
229966     47115       2018-12-01      1.000000
229967     47115       2019-01-01      1.000000
229968     47116       2018-12-01      1.000000
229969     47116       2019-01-01      1.000000
229970     47154       2019-01-01      1.000000
229971     47155       2019-01-01      1.000000
229972     47156       2019-01-01      1.000000
229973     47157       2019-01-01      0.000000
229974     47158       2019-01-01      1.000000
229975     47159       2019-01-01      1.000000
229976     47160       2019-01-01      1.000000
229977     47161       2019-01-01      0.000000
229978     47162       2019-01-01      1.000000
229979     47163       2019-01-01      1.000000
229980     47164       2019-01-01      0.000000
229981     47165       2019-01-01      0.000000
229982     47166       2019-01-01      0.000000
229983     47167       2019-01-01      0.000000
229984     47168       2019-01-01      1.000000
229985     47169       2019-01-01      1.000000
229986     47170       2019-01-01      1.000000
229987     47171       2019-01-01      0.000000
229988     47172       2019-01-01      0.000000
229989     47173       2019-01-01      1.000000
229990     47174       2019-01-01      1.000000
229991     47175       2019-01-01      1.000000
229992     47176       2019-01-01      1.000000
229993     47177       2019-01-01      1.000000
229994     47610       2019-01-01      1.000000

[229995 rows x 3 columns]

In [39]:
df = pd.merge(df,
            resumen_consorcios,
            left_on=["expensa_mes_pago_anterior","consorcio_id"],
            right_on=["expensa_mes_pago", "consorcio_id"],
            how = "left")

In [40]:
df = pd.merge(df,
            resumen_unidades,
            left_on=["expensa_mes_pago_anterior","unidad_id"],
            right_on=["expensa_mes_pago", "unidad_id"],
            how = "left")

In [41]:
df.columns = ['consorcio_id', 'consorcio_nombre', 'unidad_id', 'unidad_denominacion',
       'unidad_tipo', 'expensa_id', 'expensa_proporcion', 'expensa_mes',
       'expensa_fecha', 'expensa_mes_pago', 'expensa_version',
       'expensa_concepto', 'pago_fecha', 'pago_metodo', 'target',
       'expensa_mes_pago_anterior', 'consorcio_impagos', 'consorcio_cantidad_expensas',
       'consorcio_cantidad_efectivo', 'consorcio_prop_impagos', 'consorcio_prop_efectivo',
       'expensa_mes_pago_y', 'unidad_prop_impagos']

In [42]:
model_df = df[['expensa_id', 'consorcio_id', 'consorcio_nombre', 'unidad_id', 'unidad_denominacion',
       'unidad_tipo', 'expensa_proporcion', 'expensa_mes',
       'expensa_fecha', 'expensa_mes_pago', 'expensa_version',
       'expensa_concepto', 
       'expensa_mes_pago_anterior', 'consorcio_impagos', 'consorcio_cantidad_expensas',
       'consorcio_cantidad_efectivo', 'consorcio_prop_impagos', 'consorcio_prop_efectivo',
       'unidad_prop_impagos','target']]

In [43]:
model_df.isna().sum()

expensa_id                         0
consorcio_id                       0
consorcio_nombre                   0
unidad_id                          0
unidad_denominacion                0
unidad_tipo                        0
expensa_proporcion                 0
expensa_mes                        0
expensa_fecha                      0
expensa_mes_pago                   0
expensa_version                    0
expensa_concepto                   0
expensa_mes_pago_anterior          0
consorcio_impagos              15816
consorcio_cantidad_expensas    15816
consorcio_cantidad_efectivo    15816
consorcio_prop_impagos         15816
consorcio_prop_efectivo        15816
unidad_prop_impagos            16952
target                             0
dtype: int64

In [44]:
model_df.shape

(230845, 20)

In [45]:
X = model_df[["expensa_mes_pago","unidad_tipo", "expensa_proporcion", "expensa_mes", "expensa_version", "expensa_concepto", "consorcio_cantidad_expensas", "consorcio_prop_impagos", "consorcio_prop_efectivo", "unidad_prop_impagos", "target"]]

In [46]:
X.dtypes

expensa_mes_pago               datetime64[ns]
unidad_tipo                            object
expensa_proporcion                    float64
expensa_mes                            object
expensa_version                        object
expensa_concepto                       object
consorcio_cantidad_expensas           float64
consorcio_prop_impagos                float64
consorcio_prop_efectivo               float64
unidad_prop_impagos                   float64
target                                float64
dtype: object

In [47]:
X = X.dropna()

In [48]:
X.isna().sum()

expensa_mes_pago               0
unidad_tipo                    0
expensa_proporcion             0
expensa_mes                    0
expensa_version                0
expensa_concepto               0
consorcio_cantidad_expensas    0
consorcio_prop_impagos         0
consorcio_prop_efectivo        0
unidad_prop_impagos            0
target                         0
dtype: int64

In [49]:
X.shape

(213893, 11)

In [50]:
X = X.sort_values("expensa_mes_pago")

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test, idx_train, idx_test= train_test_split(X.drop(columns=["expensa_mes_pago", "target"]), X["target"], list(np.arange(0, len(X))), test_size=0.2, shuffle = False)

In [52]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(X_train[["consorcio_cantidad_expensas"]])

MinMaxScaler(copy=True, feature_range=(0, 1))

In [53]:
X_train["consorcio_cantidad_expensas"]= scaler.transform(X_train[["consorcio_cantidad_expensas"]])
X_test["consorcio_cantidad_expensas"]= scaler.transform(X_test[["consorcio_cantidad_expensas"]])

In [54]:
X_train.expensa_proporcion = X_train.expensa_proporcion / 100
X_test.expensa_proporcion = X_test.expensa_proporcion / 100

In [55]:
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)

In [56]:
X_train

,expensa_proporcion,consorcio_cantidad_expensas,consorcio_prop_impagos,consorcio_prop_efectivo,unidad_prop_impagos,unidad_tipo_Baulera,unidad_tipo_Casa,unidad_tipo_Cochera,unidad_tipo_Departamento,unidad_tipo_Duplex,...,expensa_mes_11,expensa_mes_12,expensa_version_1,expensa_version_2,expensa_version_3,expensa_version_4,expensa_version_5,expensa_concepto_1,expensa_concepto_10,expensa_concepto_599
1,0.032916,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
1021,0.034492,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
961,0.081054,0.067496,0.923077,0.076923,1.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
901,0.023846,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
841,0.038612,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
781,0.081054,0.067496,0.923077,0.076923,1.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
721,0.034492,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
661,0.023846,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
601,0.038612,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
541,0.034492,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
481,0.023846,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
421,0.038612,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
361,0.034492,0.067496,0.923077,0.076923,0.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
301,0.053951,0.067496,0.923077,0.076923,1.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
241,0.023846,0.067496,0.923077,0.076923,0.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
181,0.081054,0.067496,0.923077,0.076923,1.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
1081,0.082029,0.067496,0.923077,0.076923,1.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
1141,0.089225,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
1201,0.077815,0.067496,0.923077,0.076923,0.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
2281,0.027379,0.067496,0.923077,0.076923,1.000000,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
1381,0.026443,0.067496,0.923077,0.076923,1.000000,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
1501,0.027548,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
1561,0.068905,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
1621,0.081054,0.067496,0.923077,0.076923,1.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
1681,0.069355,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
1741,0.081054,0.067496,0.923077,0.076923,1.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
1801,0.067627,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
121,0.038612,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
1321,0.084880,0.067496,0.923077,0.076923,1.000000,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
1921,0.069295,0.067496,0.923077,0.076923,1.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211495,0.008000,0.220249,0.328000,0.000000,0.000000,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
132734,0.001311,0.234458,0.112782,0.142857,0.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
166361,0.002023,0.140320,0.150000,0.162500,0.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
193224,0.005811,0.358792,0.187192,0.098522,0.100000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
132725,0.001311,0.234458,0.112782,0.142857,0.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
49208,0.004010,0.918295,0.467181,0.405405,0.022222,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
205153,0.045537,0.031972,0.105263,0.105263,0.000000,0,0,0,1,0,...,0,0,0,1,0,0,0,1,0,0
166319,0.002023,0.140320,0.150000,0.162500,0.777778,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
212237,0.008000,0.220249,0.328000,0.000000,0.000000,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
193240,0.006040,0.358792,0.187192,0.098522,0.100000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
200651,0.033025,0.055062,0.156250,0.281250,0.375000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
200759,0.006078,0.134991,0.233766,0.311688,0.000000,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
132608,0.001157,0.234458,0.112782,0.142857,0.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
205165,0.045537,0.031972,0.105263,0.105263,0.625000,0,0,0,1,0,...,0,0,0,1,0,0,0,1,0,0
166277,0.002023,0.140320,0.150000,0.162500,0.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
137002,0.008374,0.085258,0.204082,0.000000,0.000000,0,0,0,1,0,...,0,0,0,1,0,0,0,1,0,0
168888,0.015967,0.090586,0.076923,0.769231,0.083333,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
187068,0.056850,0.033748,0.150000,0.350000,0.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
204521,0.076030,0.028419,0.117647,0.000000,0.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
211470,0.008000,0.220249,0.328000,0.000000,0.000000,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
132599,0.001080,0.234458,0.112782,0.142857,0.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
1855,0.066013,0.072824,0.119048,0.000000,0.036364,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
212271,0.008000,0.220249,0.328000,0.000000,0.250000,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
193256,0.005126,0.358792,0.187192,0.098522,0.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
132590,0.001080,0.234458,0.112782,0.142857,0.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
137024,0.008877,0.085258,0.204082,0.000000,0.055556,0,0,0,1,0,...,0,0,0,1,0,0,0,1,0,0
166263,0.002075,0.140320,0.150000,0.162500,0.000000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
168905,0.025092,0.090586,0.076923,0.769231,0.000000,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
49308,0.005460,0.918295,0.467181,0.405405,1.000000,0,0,0,0,1,...,0,0,1,0,0,0,0,1,0,0
132581,0.000957,0.234458,0.112782,0.142857,0.750000,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0

In [57]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, Y_train)

C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [58]:
model.score(X_train, Y_train)

0.8500239606344309

In [59]:
for column in [column for column in X_train.columns if column not in X_test.columns]:
    X_test[column] = 0

In [60]:
model.score(X_test, Y_test)

0.8465602281493256

In [61]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_train, model.predict(X_train)))
confusion_matrix(Y_test, model.predict(X_test))

[[116859   8746]
 [ 16917  28592]]

array([[29457,  2720],
       [ 3844,  6758]], dtype=int64)

In [62]:
columns_coeficients = pd.DataFrame({
    "var":X_train.columns,
    "coef":model.coef_[0],
})

In [63]:
columns_coeficients

                            var      coef
0            expensa_proporcion  0.674467
1   consorcio_cantidad_expensas -0.167668
2        consorcio_prop_impagos  1.395901
3       consorcio_prop_efectivo  0.165930
4           unidad_prop_impagos  4.325465
5           unidad_tipo_Baulera  0.209904
6              unidad_tipo_Casa -0.558065
7           unidad_tipo_Cochera -0.324013
8      unidad_tipo_Departamento -0.353268
9            unidad_tipo_Duplex -0.206677
10            unidad_tipo_Local -0.049391
11             unidad_tipo_Lote -0.190253
12          unidad_tipo_Oficina -0.330981
13               expensa_mes_01 -0.074429
14               expensa_mes_02 -0.076865
15               expensa_mes_03 -0.137317
16               expensa_mes_04 -0.220597
17               expensa_mes_05 -0.158301
18               expensa_mes_06 -0.216674
19               expensa_mes_07 -0.224884
20               expensa_mes_08 -0.195351
21               expensa_mes_09 -0.187793
22               expensa_mes_10 -0.143970
23               expensa_mes_11 -0.063893
24               expensa_mes_12 -0.102669
25            expensa_version_1 -0.452279
26            expensa_version_2 -0.474969
27            expensa_version_3 -0.698194
28            expensa_version_4 -0.672044
29            expensa_version_5  0.494741
30           expensa_concepto_1 -0.378447
31          expensa_concepto_10 -0.549911
32         expensa_concepto_599 -0.874386

In [64]:
_,_, id_train, id_val = train_test_split(X_train, list(np.arange(0, len(X_train))), test_size=0.2, shuffle=False)

In [65]:
from sklearn.linear_model import LogisticRegressionCV

linear_modelCV = LogisticRegressionCV(
    cv = [(id_train, id_val)],
    scoring = "f1",
    n_jobs = -1,
    verbose = 5,
    refit = True,
)

In [120]:
linear_modelCV.fit(X_train.values, Y_train)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 out of   1 | elapsed:   18.3s finished

LogisticRegressionCV(Cs=10, class_weight=None,
           cv=[([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, ...1, 171102, 171103, 171104, 171105, 171106, 171107, 171108, 171109, 171110, 171111, 171112, 171113])],
           dual=False, fit_intercept=True, intercept_scaling=1.0,
           max_iter=100, multi_class='warn', n_jobs=-1, penalty='l2',
           random_state=None, refit=True, scoring='f1', solver='lbfgs',
           tol=0.0001, verbose=5)

In [67]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
train_preds = linear_modelCV.predict(X_train)
print("accuracy:", accuracy_score(Y_train, train_preds))
print("precision:", precision_score(Y_train, train_preds))
print("recall:", recall_score(Y_train, train_preds))

accuracy: 0.8500122725200744
precision: 0.7656919451585261
recall: 0.6283152782966007

In [68]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
test_preds = linear_modelCV.predict(X_test)
print("accuracy:", accuracy_score(Y_test, test_preds))
print("precision:", precision_score(Y_test, test_preds))
print("recall:", recall_score(Y_test, test_preds))

accuracy: 0.8513055471142383
precision: 0.7818689352651867
recall: 0.5548009809469912

In [69]:
columns_coeficients = pd.DataFrame({
    "var":X_train.columns,
    "coef":linear_modelCV.coef_[0],
})

In [70]:
columns_coeficients

                            var      coef
0            expensa_proporcion  0.740481
1   consorcio_cantidad_expensas -0.164723
2        consorcio_prop_impagos  1.395160
3       consorcio_prop_efectivo  0.165968
4           unidad_prop_impagos  4.327268
5           unidad_tipo_Baulera  0.435521
6              unidad_tipo_Casa -0.333934
7           unidad_tipo_Cochera -0.097876
8      unidad_tipo_Departamento -0.127585
9            unidad_tipo_Duplex  0.017391
10            unidad_tipo_Local  0.175983
11             unidad_tipo_Lote  0.037591
12          unidad_tipo_Oficina -0.106677
13               expensa_mes_01  0.075860
14               expensa_mes_02  0.073421
15               expensa_mes_03  0.013042
16               expensa_mes_04 -0.070361
17               expensa_mes_05 -0.008006
18               expensa_mes_06 -0.066332
19               expensa_mes_07 -0.074604
20               expensa_mes_08 -0.045033
21               expensa_mes_09 -0.037436
22               expensa_mes_10  0.005844
23               expensa_mes_11  0.086278
24               expensa_mes_12  0.047739
25            expensa_version_1 -0.094209
26            expensa_version_2 -0.117294
27            expensa_version_3 -0.343191
28            expensa_version_4 -0.322830
29            expensa_version_5  0.877937
30           expensa_concepto_1  0.227639
31          expensa_concepto_10  0.053190
32         expensa_concepto_599 -0.280415

In [92]:
test_all_features = model_df.dropna()
test_all_features = test_all_features.sort_values("expensa_mes_pago")
test_all_features = test_all_features[len(idx_train):]

In [93]:
test_all_features[:10]

,expensa_id,consorcio_id,consorcio_nombre,unidad_id,unidad_denominacion,unidad_tipo,expensa_proporcion,expensa_mes,expensa_fecha,expensa_mes_pago,expensa_version,expensa_concepto,expensa_mes_pago_anterior,consorcio_impagos,consorcio_cantidad_expensas,consorcio_cantidad_efectivo,consorcio_prop_impagos,consorcio_prop_efectivo,unidad_prop_impagos,target
212280,301092,1757,LA CERCANIA - BARRIO CERRADO,38642,0723,Lote,0.800000,09,2018-09-01,2018-09-01,1,1,2018-08-01,41.0,125.0,0.0,0.328000,0.000000,0.000000,0.0
212263,301090,1757,LA CERCANIA - BARRIO CERRADO,38640,0721,Lote,0.800000,09,2018-09-01,2018-09-01,1,1,2018-08-01,41.0,125.0,0.0,0.328000,0.000000,0.000000,0.0
212369,301103,1757,LA CERCANIA - BARRIO CERRADO,39449,0116,Lote,0.800000,09,2018-09-01,2018-09-01,1,1,2018-08-01,41.0,125.0,0.0,0.328000,0.000000,0.250000,1.0
220983,298113,1806,Victoria II,40661,3°B,Departamento,2.731431,08,2018-08-01,2018-09-01,1,1,2018-08-01,2.0,27.0,22.0,0.074074,0.814815,0.000000,0.0
168871,295730,1638,ASTRO,33087,5ºE,Departamento,1.110833,08,2018-08-01,2018-09-01,1,1,2018-08-01,4.0,52.0,40.0,0.076923,0.769231,0.000000,0.0
132662,308698,1568,Consorcio Livette Chateau,39428,T2 - COCH SS 15,Cochera,0.123393,08,2018-08-01,2018-09-01,1,1,2018-08-01,15.0,133.0,19.0,0.112782,0.142857,0.000000,0.0
136936,305275,1584,Florida XXV,30342,8°y 9º DUPLEX,Departamento,1.022831,09,2018-09-01,2018-09-01,2,1,2018-08-01,10.0,49.0,0.0,0.204082,0.000000,0.166667,0.0
168837,295728,1638,ASTRO,33085,5ºC,Departamento,2.440000,08,2018-08-01,2018-09-01,1,1,2018-08-01,4.0,52.0,40.0,0.076923,0.769231,0.000000,0.0
49258,298759,827,Coppar,13811,0508E,Departamento,0.401000,08,2018-08-01,2018-09-01,1,1,2018-08-01,242.0,518.0,210.0,0.467181,0.405405,0.777778,0.0
136958,305281,1584,Florida XXV,30343,8°y 9º DUPLEX B,Departamento,0.949422,09,2018-09-01,2018-09-01,2,1,2018-08-01,10.0,49.0,0.0,0.204082,0.000000,0.277778,0.0

In [95]:
test_all_features["predicted"] = test_preds

In [96]:
test_all_features[['expensa_id', 'consorcio_id', 'consorcio_nombre', 'unidad_id', 'unidad_denominacion',
       'unidad_tipo', 'expensa_proporcion', 'expensa_mes',
       'expensa_fecha', 'expensa_mes_pago', 'consorcio_impagos', 'consorcio_cantidad_expensas',
       'consorcio_cantidad_efectivo', 'consorcio_prop_impagos', 'consorcio_prop_efectivo',
       'unidad_prop_impagos','target', 'predicted']]

,expensa_id,consorcio_id,consorcio_nombre,unidad_id,unidad_denominacion,unidad_tipo,expensa_proporcion,expensa_mes,expensa_fecha,expensa_mes_pago,consorcio_impagos,consorcio_cantidad_expensas,consorcio_cantidad_efectivo,consorcio_prop_impagos,consorcio_prop_efectivo,unidad_prop_impagos,target,predicted
212280,301092,1757,LA CERCANIA - BARRIO CERRADO,38642,0723,Lote,0.800000,09,2018-09-01,2018-09-01,41.0,125.0,0.0,0.328000,0.000000,0.000000,0.0,0.0
212263,301090,1757,LA CERCANIA - BARRIO CERRADO,38640,0721,Lote,0.800000,09,2018-09-01,2018-09-01,41.0,125.0,0.0,0.328000,0.000000,0.000000,0.0,0.0
212369,301103,1757,LA CERCANIA - BARRIO CERRADO,39449,0116,Lote,0.800000,09,2018-09-01,2018-09-01,41.0,125.0,0.0,0.328000,0.000000,0.250000,1.0,0.0
220983,298113,1806,Victoria II,40661,3°B,Departamento,2.731431,08,2018-08-01,2018-09-01,2.0,27.0,22.0,0.074074,0.814815,0.000000,0.0,0.0
168871,295730,1638,ASTRO,33087,5ºE,Departamento,1.110833,08,2018-08-01,2018-09-01,4.0,52.0,40.0,0.076923,0.769231,0.000000,0.0,0.0
132662,308698,1568,Consorcio Livette Chateau,39428,T2 - COCH SS 15,Cochera,0.123393,08,2018-08-01,2018-09-01,15.0,133.0,19.0,0.112782,0.142857,0.000000,0.0,0.0
136936,305275,1584,Florida XXV,30342,8°y 9º DUPLEX,Departamento,1.022831,09,2018-09-01,2018-09-01,10.0,49.0,0.0,0.204082,0.000000,0.166667,0.0,0.0
168837,295728,1638,ASTRO,33085,5ºC,Departamento,2.440000,08,2018-08-01,2018-09-01,4.0,52.0,40.0,0.076923,0.769231,0.000000,0.0,0.0
49258,298759,827,Coppar,13811,0508E,Departamento,0.401000,08,2018-08-01,2018-09-01,242.0,518.0,210.0,0.467181,0.405405,0.777778,0.0,1.0
136958,305281,1584,Florida XXV,30343,8°y 9º DUPLEX B,Departamento,0.949422,09,2018-09-01,2018-09-01,10.0,49.0,0.0,0.204082,0.000000,0.277778,0.0,0.0
211478,300997,1757,LA CERCANIA - BARRIO CERRADO,38547,0207,Lote,0.800000,09,2018-09-01,2018-09-01,41.0,125.0,0.0,0.328000,0.000000,0.750000,1.0,1.0
220976,298112,1806,Victoria II,40660,3°A,Departamento,4.354190,08,2018-08-01,2018-09-01,2.0,27.0,22.0,0.074074,0.814815,0.000000,0.0,0.0
132653,308697,1568,Consorcio Livette Chateau,39427,T2 - COCH SS 14,Cochera,0.115680,08,2018-08-01,2018-09-01,15.0,133.0,19.0,0.112782,0.142857,0.000000,0.0,0.0
187446,306272,1683,Italia 1123,35727,01-02,Departamento,2.672732,08,2018-08-01,2018-09-01,7.0,31.0,6.0,0.225806,0.193548,0.333333,0.0,0.0
166305,300063,1635,Buen Ayre,32843,PH 7 - CH7,Cochera,0.182069,08,2018-08-01,2018-09-01,12.0,80.0,13.0,0.150000,0.162500,0.333333,0.0,0.0
212245,301088,1757,LA CERCANIA - BARRIO CERRADO,38638,0719,Lote,0.800000,09,2018-09-01,2018-09-01,41.0,125.0,0.0,0.328000,0.000000,0.000000,0.0,0.0
132644,308696,1568,Consorcio Livette Chateau,39426,T2 - COCH SS 13,Cochera,0.123393,08,2018-08-01,2018-09-01,15.0,133.0,19.0,0.112782,0.142857,0.750000,1.0,1.0
168854,295729,1638,ASTRO,33086,5ºD,Departamento,1.904167,08,2018-08-01,2018-09-01,4.0,52.0,40.0,0.076923,0.769231,0.000000,0.0,0.0
91654,296799,1429,PEREDO PRIVATO,25242,PH59 - 4º F,Departamento,1.660513,08,2018-08-01,2018-09-01,3.0,52.0,5.0,0.057692,0.096154,0.000000,0.0,0.0
132635,308695,1568,Consorcio Livette Chateau,39425,T2 - COCH SS 12,Cochera,0.107969,08,2018-08-01,2018-09-01,15.0,133.0,19.0,0.112782,0.142857,0.000000,0.0,0.0
136980,305287,1584,Florida XXV,30344,8º DPTO. C,Departamento,0.926774,09,2018-09-01,2018-09-01,10.0,49.0,0.0,0.204082,0.000000,0.277778,0.0,0.0
63831,299050,827,Coppar,14838,PH 165,Baulera,0.026000,08,2018-08-01,2018-09-01,242.0,518.0,210.0,0.467181,0.405405,0.977778,1.0,1.0
212254,301089,1757,LA CERCANIA - BARRIO CERRADO,38639,0720,Lote,0.800000,09,2018-09-01,2018-09-01,41.0,125.0,0.0,0.328000,0.000000,0.000000,0.0,0.0
132626,308694,1568,Consorcio Livette Chateau,39424,T2 - COCH SS 11,Cochera,0.107969,08,2018-08-01,2018-09-01,15.0,133.0,19.0,0.112782,0.142857,0.000000,0.0,0.0
166291,300062,1635,Buen Ayre,32842,PH 6 - CH6,Cochera,0.172328,08,2018-08-01,2018-09-01,12.0,80.0,13.0,0.150000,0.162500,0.000000,0.0,0.0
132617,308693,1568,Consorcio Livette Chateau,39423,T2 - COCH SS 10,Cochera,0.115680,08,2018-08-01,2018-09-01,15.0,133.0,19.0,0.112782,0.142857,1.000000,1.0,1.0
192488,304052,1690,Gran Estrada III,36067,PH 119 - 6º Piso Dpto. H,Departamento,0.467232,08,2018-08-01,2018-09-01,38.0,203.0,20.0,0.187192,0.098522,0.000000,1.0,0.0
132374,308666,1568,Consorcio Livette Chateau,39396,T2 - 2º B,Departamento,2.144695,08,2018-08-01,2018-09-01,15.0,133.0,19.0,0.112782,0.142857,0.500000,0.0,0.0
137265,310235,1585,Consorcio Edificio ATLAS IV,30357,"6° A""""",Departamento,8.931260,08,2018-08-01,2018-09-01,2.0,14.0,3.0,0.142857,0.214286,0.470588,1.0,0.0
192440,304037,1690,Gran Estrada III,36064,PH 116 - 6º Piso Dpto. E,Departamento,0.603991,08,2018-08-01,2018-09-01,38.0,203.0,20.0,0.187192,0.098522,0.800000,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220182,396571,1800,Cesicar,40546,3° A,Departamento,11.854541,12,2018-12-01,2019-01-01,3.0,9.0,6.0,0.333333,0.666667,0.000000,0.0,0.0
169981,389601,1639,PLAZA COLON,33152,6 E,Departamento,1.300000,12,2018-12-01,2019-01-01,7.0,67.0,54.0,0.104478,0.805970,0.176471,0.0,0.0
94634,389745,1446,CONSROCIO LACOSTA 230,25465,PB A,Departamento,5.759007,12,2018-12-01,2019-01-01,2.0,16.0,3.0,0.125000,0.187500,0.323529,0.0,0.0
169963,389600,1639,PLAZA COLON,33151,6 D,Departamento,1.420000,12,2018-12-01,2019-01-01,7.0,67.0,54.0,0.104478,0.805970,0.062500,0.0,0.0
220175,396570,1800,Cesicar,40545,2° B,Departamento,9.109617,12,2018-12-01,2019-01-01,3.0,9.0,6.0,0.333333,0.666667,0.166667,0.0,0.0
169946,389599,1639,PLAZA COLON,33150,6 C,Departamento,1.220000,12,2018-12-01,2019-01-01,7.0,67.0,54.0,0.104478,0.805970,0.250000,1.0,0.0
94670,389746,1446,CONSROCIO LACOSTA 230,25466,PB C,Departamento,6.577278,12,2018-12-01,2019-01-01,2.0,16.0,3.0,0.125000,0.187500,0.323529,0.0,0.0
45412,386395,827,Coppar,13694,0111C,Departamento,0.216000,12,2018-12-01,2019-01-01,202.0,518.0,247.0,0.389961,0.476834,0.632653,1.0,0.0
204287,398535,1715,Consorcio Alysa I,37239,OFIC A - U.F. 6,Oficina,1.870117,12,2018-12-01,2019-01-01,26.0,154.0,1.0,0.168831,0.006494,0.769231,1.0,1.0
220168,396569,1800,Cesicar,40544,2° A,Departamento,11.854541,12,2018-12-01,2019-01-01,3.0,9.0,6.0,0.333333,0.666667,0.000000,0.0,0.0
169929,389598,1639,PLAZA COLON,33149,6 B,Departamento,1.250270,12,2018-12-01,2019-01-01,7.0,67.0,54.0,0.104478,0.805970,0.000000,0.0,0.0
169912,389597,1639,PLAZA COLON,33148,6 A,Departamento,2.780000,12,2018-12-01,2019-01-01,7.0,67.0,54.0,0.104478,0.805970,0.000000,0.0,0.0
94705,389747,1446,CONSROCIO LACOSTA 230,25467,PB D,Departamento,6.577278,12,2018-12-01,2019-01-01,2.0,16.0,3.0,0.125000,0.187500,0.088235,0.0,0.0
220161,396568,1800,Cesicar,40543,1° Piso,Departamento,22.970682,12,2018-12-01,2019-01-01,3.0,9.0,6.0,0.333333,0.666667,0.166667,0.0,0.0
45262,386392,827,Coppar,13685,LSS4A,Local,0.500000,12,2018-12-01,2019-01-01,202.0,518.0,247.0,0.389961,0.476834,0.775510,0.0,1.0
169827,389590,1639,PLAZA COLON,33143,5 C,Departamento,1.220000,12,2018-12-01,2019-01-01,7.0,67.0,54.0,0.104478,0.805970,0.000000,0.0,0.0
220140,387986,1798,MAISON I,40540,Cochera 4,Cochera,5.482132,12,2018-12-01,2019-01-01,4.0,20.0,13.0,0.200000,0.650000,0.000000,0.0,0.0
94775,389749,1446,CONSROCIO LACOSTA 230,25469,1º A,Departamento,6.577278,12,2018-12-01,2019-01-01,2.0,16.0,3.0,0.125000,0.187500,0.617647,1.0,0.0
169844,389592,1639,PLAZA COLON,33144,5 D,Departamento,1.420000,12,2018-12-01,2019-01-01,7.0,67.0,54.0,0.104478,0.805970,0.000000,0.0,0.0
169861,389593,1639,PLAZA COLON,33145,5 E,Departamento,1.300000,12,2018-12-01,2019-01-01,7.0,67.0,54.0,0.104478,0.805970,0.000000,0.0,0.0
220189,396572,1800,Cesicar,40547,3° B,Departamento,9.109617,12,2018-12-01,2019-01-01,3.0,9.0,6.0,0.333333,0.666667,0.000000,0.0,0.0
220147,396566,1800,Cesicar,40541,Local 1,Local,7.480320,12,2018-12-01,2019-01-01,3.0,9.0,6.0,0.333333,0.666667,1.000000,1.0,1.0
94740,389748,1446,CONSROCIO LACOSTA 230,25468,1º B,Departamento,6.577278,12,2018-12-01,2019-01-01,2.0,16.0,3.0,0.125000,0.187500,0.000000,0.0,0.0
169878,389595,1639,PLAZA COLON,33146,5 F,Departamento,1.120000,12,2018-12-01,2019-01-01,7.0,67.0,54.0,0.104478,0.805970,0.000000,0.0,0.0
204301,398538,1715,Consorcio Alysa I,37240,OFIC B - U.F. 7,Oficina,1.956697,12,2018-12-01,2019-01-01,26.0,154.0,1.0,0.168831,0.006494,0.076923,0.0,0.0
220154,396567,1800,Cesicar,40542,Local 2,Local,6.653632,12,2018-12-01,2019-01-01,3.0,9.0,6.0,0.333333,0.666667,0.166667,0.0,0.0
169895,389596,1639,PLAZA COLON,33147,5 G,Departamento,1.440000,12,2018-12-01,2019-01-01,7.0,67.0,54.0,0.104478,0.805970,0.000000,0.0,0.0
45362,386394,827,Coppar,13690,0104F,Departamento,0.401000,12,2018-12-01,2019-01-01,202.0,518.0,247.0,0.389961,0.476834,0.326531,0.0,0.0
45312,386393,827,Coppar,13689,0107E,Departamento,0.401000,12,2018-12-01,2019-01-01,202.0,518.0,247.0,0.389961,0.476834,0.857143,0.0,1.0
230819,432706,2033,Sunchales Monobloc N° 2 Manzana 591,47116,Segundo Piso - UFP 108,Departamento,1.330598,12,2018-12-01,2019-01-01,54.0,54.0,0.0,1.000000,0.000000,1.000000,1.0,1.0

In [97]:
results_by_consorcio = test_all_features[["consorcio_id","consorcio_nombre","target","predicted"]]

In [102]:
results_by_consorcio["TP"] = test_all_features.target.map(bool) & test_all_features.predicted.map(bool)
results_by_consorcio["TN"] = ~test_all_features.target.map(bool) & ~test_all_features.predicted.map(bool)
results_by_consorcio["FP"] = ~test_all_features.target.map(bool) & test_all_features.predicted.map(bool)
results_by_consorcio["FN"] = test_all_features.target.map(bool) & ~test_all_features.predicted.map(bool)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [105]:
results_by_consorcio = results_by_consorcio.groupby(["consorcio_id","consorcio_nombre"]).sum()

In [106]:
results_by_consorcio["Total"] = results_by_consorcio.TP + results_by_consorcio.TN + results_by_consorcio.FP + results_by_consorcio.FN
results_by_consorcio["PP"] = results_by_consorcio.TP + results_by_consorcio.FP
results_by_consorcio["PN"] = results_by_consorcio.TN + results_by_consorcio.FN
results_by_consorcio["RP"] = results_by_consorcio.TP + results_by_consorcio.FN
results_by_consorcio["RN"] = results_by_consorcio.FP + results_by_consorcio.TN

In [107]:
results_by_consorcio["accuracy"] = (results_by_consorcio.TP + results_by_consorcio.TN)/results_by_consorcio.Total
results_by_consorcio["precision"] = (results_by_consorcio.TP)/results_by_consorcio.PP
results_by_consorcio["recall"] = results_by_consorcio.TP / results_by_consorcio.RP

In [112]:
results_by_consorcio[["TP","TN","FP","FN", "Total","accuracy", "precision", "recall"]].sort_values("Total", ascending = False)

,,TP,TN,FP,FN,Total,accuracy,precision,recall
consorcio_id,consorcio_nombre,,,,,,,,
827,Coppar,711.0,968.0,221.0,310.0,2210.0,0.759729,0.762876,0.696376
1796,El Sol S.A.I.C. y .F.,321.0,1146.0,79.0,160.0,1706.0,0.859906,0.802500,0.667360
1598,Tejas Dos,95.0,1367.0,11.0,145.0,1618.0,0.903585,0.896226,0.395833
1648,Altos Y Bosques de Catalina,344.0,714.0,110.0,167.0,1335.0,0.792509,0.757709,0.673190
1672,Tejas del Sur Cuatro SA,138.0,653.0,17.0,132.0,940.0,0.841489,0.890323,0.511111
1690,Gran Estrada III,75.0,677.0,39.0,84.0,875.0,0.859429,0.657895,0.471698
1618,Jardin Claret,44.0,650.0,4.0,55.0,753.0,0.921647,0.916667,0.444444
1750,Sierra Nueva,514.0,130.0,72.0,19.0,735.0,0.876190,0.877133,0.964353
1807,Stella Maris II y III,105.0,494.0,30.0,90.0,719.0,0.833102,0.777778,0.538462
1715,Consorcio Alysa I,30.0,567.0,15.0,53.0,665.0,0.897744,0.666667,0.361446
1568,Consorcio Livette Chateau,41.0,492.0,5.0,36.0,574.0,0.928571,0.891304,0.532468
1644,Portofino I,26.0,496.0,7.0,22.0,551.0,0.947368,0.787879,0.541667
518,ACONCAGUA,133.0,321.0,18.0,66.0,538.0,0.843866,0.880795,0.668342
1797,Plaza Caviahue,21.0,435.0,5.0,51.0,512.0,0.890625,0.807692,0.291667
1695,Puente Blanco,18.0,407.0,6.0,57.0,488.0,0.870902,0.750000,0.240000
1626,CONSORCIO INARCO 25,1.0,404.0,3.0,44.0,452.0,0.896018,0.250000,0.022222
1407,Balcones de cofico III,3.0,395.0,1.0,34.0,433.0,0.919169,0.750000,0.081081
1630,CONSORCIO INARCO 28,8.0,360.0,10.0,32.0,410.0,0.897561,0.444444,0.200000
1757,LA CERCANIA - BARRIO CERRADO,45.0,257.0,42.0,50.0,394.0,0.766497,0.517241,0.473684
742,EDIFICIO SUSSEX I,19.0,302.0,5.0,50.0,376.0,0.853723,0.791667,0.275362
1629,CONSORCIO INARCO 27,2.0,336.0,6.0,16.0,360.0,0.938889,0.250000,0.111111
1631,CONSORCIO INARCO 29,0.0,343.0,0.0,15.0,358.0,0.958101,NaN,0.000000
1527,MARIA REINA V,14.0,288.0,2.0,40.0,344.0,0.877907,0.875000,0.259259
1623,CONSORCIO INARCO 22,16.0,313.0,0.0,11.0,340.0,0.967647,1.000000,0.592593
1726,Villa Veneto - Altos del Río,12.0,314.0,0.0,14.0,340.0,0.958824,1.000000,0.461538
1713,COMPLEJO LAS DOS TORRES,39.0,197.0,20.0,72.0,328.0,0.719512,0.661017,0.351351
1635,Buen Ayre,18.0,247.0,15.0,42.0,322.0,0.822981,0.545455,0.300000
1621,CONSORCIO INARCO 20,15.0,280.0,9.0,16.0,320.0,0.921875,0.625000,0.483871
1617,MARIA REINA X,11.0,239.0,3.0,51.0,304.0,0.822368,0.785714,0.177419
1538,CONSORCIO EDIFICIO GAUDI,15.0,235.0,4.0,41.0,295.0,0.847458,0.789474,0.267857
...,...,...,...,...,...,...,...,...,...
1756,Jeronimo Cortes,24.0,0.0,0.0,0.0,24.0,1.000000,1.000000,1.000000
1965,SUR I,5.0,14.0,4.0,1.0,24.0,0.791667,0.555556,0.833333
2006,CAUDILLOS V,4.0,15.0,1.0,3.0,23.0,0.826087,0.800000,0.571429
1876,Consorcio de Propietarios de Calle 27 de Abril,0.0,15.0,1.0,6.0,22.0,0.681818,0.000000,0.000000
1906,Consorcio Idaniko Extraordinarias,6.0,13.0,1.0,1.0,21.0,0.904762,0.857143,0.857143
1819,CONSORCIO PROPIETARIOS AV. MITRE 857 859,0.0,20.0,0.0,0.0,20.0,1.000000,NaN,NaN
1963,General Lopez 2960,1.0,12.0,5.0,2.0,20.0,0.650000,0.166667,0.333333
1959,Consorcio 25 de mayo 1972,1.0,13.0,2.0,2.0,18.0,0.777778,0.333333,0.333333
1529,Sucre Nº 2325,0.0,16.0,0.0,2.0,18.0,0.888889,NaN,0.000000
1993,MENDOZA - EXTRAORDINARIAS,4.0,11.0,2.0,1.0,18.0,0.833333,0.666667,0.800000
1791,RIZZOMAR VI,6.0,3.0,3.0,6.0,18.0,0.500000,0.666667,0.500000
2016,317 CB,7.0,5.0,4.0,1.0,17.0,0.705882,0.636364,0.875000
1805,Tucuman,4.0,10.0,0.0,2.0,16.0,0.875000,1.000000,0.666667
1964,TIEMPO I,0.0,15.0,0.0,0.0,15.0,1.000000,NaN,NaN
2007,CELESTINO I,0.0,7.0,2.0,4.0,13.0,0.538462,0.000000,0.000000
2005,LEGISLATURA,6.0,3.0,4.0,0.0,13.0,0.692308,0.600000,1.000000
2011,JUAN DEL CAMPILLO EXTRAORDINARIAS,1.0,4.0,7.0,0.0,12.0,0.416667,0.125000,1.000000
1975,JUAN DEL CAMPILLO,0.0,5.0,7.0,0.0,12.0,0.416667,0.000000,NaN
1881,Consorcio 24 de Septiembre 756,0.0,8.0,0.0,4.0,12.0,0.666667,NaN,0.000000
1892,EDIFICIO EMILIO MUSICANT,2.0,6.0,1.0,1.0,10.0,0.800000,0.666667,0.666667
1986,4 DE ENERO 2521,0.0,9.0,0.0,0.0,9.0,1.000000,NaN,NaN
1971,4 DE ENERO 3657,3.0,4.0,0.0,1.0,8.0,0.875000,1.000000,0.750000
1989,LEAN I,2.0,2.0,2.0,2.0,8.0,0.500000,0.500000,0.500000
1998,EDIFICIO IV - PRO.CRE.AR BASAMENTO 1,4.0,3.0,1.0,0.0,8.0,0.875000,0.800000,1.000000
1982,CATAMARCA 3528/30,3.0,0.0,4.0,0.0,7.0,0.428571,0.428571,1.000000
1985,1 DE MAYO 5113,1.0,6.0,0.0,0.0,7.0,1.000000,1.000000,1.000000
1977,1 JUNTA 3422,2.0,3.0,1.0,0.0,6.0,0.833333,0.666667,1.000000
1897,PROPIETARIOS EMILIO MUSICANT,5.0,0.0,0.0,0.0,5.0,1.000000,1.000000,1.000000
1961,LAGO,0.0,4.0,1.0,0.0,5.0,0.800000,0.000000,NaN
1984,SAN MARTIN 1767,2.0,1.0,1.0,0.0,4.0,0.750000,0.666667,1.000000

In [116]:
data.loc[(data.consorcio_id == "1715") & (data.expensa_mes_pago > "2018-01-01")]

,consorcio_id,consorcio_fecha_creacion,consorcio_nombre,consorcio_modo_pago,consorcio_visibilidad_gasto,consorcio_tipo,consorcio_usa_fondo,consorcio_solo_muestra_cat,unidad_id,unidad_denominacion,...,expensa_mes,expensa_anio,expensa_version,expensa_concepto,pago_fecha,pago_monto,pago_metodo,expensa_fecha,expensa_mes_pago,target
201674,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37097,DEPTO. Nº 14A - U.F. 92,...,01,2018,1,1,2018-02-15,0.00,Efectivo,2018-01-01,2018-02-01,0.0
201675,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37097,DEPTO. Nº 14A - U.F. 92,...,02,2018,1,1,2018-03-08,959.66,Pago Mis Cuentas,2018-02-01,2018-03-01,0.0
201676,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37097,DEPTO. Nº 14A - U.F. 92,...,03,2018,2,1,2018-04-09,1225.91,Pago Mis Cuentas,2018-03-01,2018-04-01,0.0
201677,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37097,DEPTO. Nº 14A - U.F. 92,...,04,2018,1,1,2018-05-05,1347.99,Pago Mis Cuentas,2018-04-01,2018-05-01,0.0
201678,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37097,DEPTO. Nº 14A - U.F. 92,...,05,2018,1,1,2018-06-06,1284.38,Pago Mis Cuentas,2018-05-01,2018-06-01,0.0
201679,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37097,DEPTO. Nº 14A - U.F. 92,...,06,2018,2,1,2018-07-07,1566.99,Pago Mis Cuentas,2018-06-01,2018-07-01,0.0
201680,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37097,DEPTO. Nº 14A - U.F. 92,...,07,2018,1,1,2018-08-04,1431.45,Pago Mis Cuentas,2018-07-01,2018-08-01,0.0
201681,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37097,DEPTO. Nº 14A - U.F. 92,...,08,2018,1,1,2018-09-06,1721.78,Pago Mis Cuentas,2018-08-01,2018-09-01,0.0
201682,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37097,DEPTO. Nº 14A - U.F. 92,...,09,2018,1,1,2018-10-05,1603.65,Pago Mis Cuentas,2018-09-01,2018-10-01,0.0
201683,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37097,DEPTO. Nº 14A - U.F. 92,...,10,2018,1,1,2018-11-09,1633.21,Pago Mis Cuentas,2018-10-01,2018-11-01,0.0
201684,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37097,DEPTO. Nº 14A - U.F. 92,...,11,2018,1,1,2018-12-14,1815.87,Pago Mis Cuentas,2018-11-01,2018-12-01,0.0
201685,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37097,DEPTO. Nº 14A - U.F. 92,...,12,2018,1,1,2019-01-08,2346.67,Pago Mis Cuentas,2018-12-01,2019-01-01,0.0
201687,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37098,COCHERA N°13 - U.C. AK,...,01,2018,1,1,2018-02-15,447.16,Efectivo,2018-01-01,2018-02-01,0.0
201688,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37098,COCHERA N°13 - U.C. AK,...,02,2018,1,1,2018-03-08,517.86,Pago Mis Cuentas,2018-02-01,2018-03-01,0.0
201689,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37098,COCHERA N°13 - U.C. AK,...,03,2018,2,1,2018-04-09,423.33,Pago Mis Cuentas,2018-03-01,2018-04-01,0.0
201690,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37098,COCHERA N°13 - U.C. AK,...,04,2018,1,1,2018-05-05,465.66,Pago Mis Cuentas,2018-04-01,2018-05-01,0.0
201691,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37098,COCHERA N°13 - U.C. AK,...,05,2018,1,1,2018-06-06,443.62,Pago Mis Cuentas,2018-05-01,2018-06-01,0.0
201692,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37098,COCHERA N°13 - U.C. AK,...,06,2018,2,1,2018-07-07,541.67,Pago Mis Cuentas,2018-06-01,2018-07-01,0.0
201693,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37098,COCHERA N°13 - U.C. AK,...,07,2018,1,1,2018-08-04,502.39,Pago Mis Cuentas,2018-07-01,2018-08-01,0.0
201694,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37098,COCHERA N°13 - U.C. AK,...,08,2018,1,1,2018-09-06,598.21,Pago Mis Cuentas,2018-08-01,2018-09-01,0.0
201695,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37098,COCHERA N°13 - U.C. AK,...,09,2018,1,1,2018-10-05,554.23,Pago Mis Cuentas,2018-09-01,2018-10-01,0.0
201696,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37098,COCHERA N°13 - U.C. AK,...,10,2018,1,1,2018-11-09,564.27,Pago Mis Cuentas,2018-10-01,2018-11-01,0.0
201697,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37098,COCHERA N°13 - U.C. AK,...,11,2018,1,1,2018-12-14,627.61,Pago Mis Cuentas,2018-11-01,2018-12-01,0.0
201698,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37098,COCHERA N°13 - U.C. AK,...,12,2018,1,1,2019-01-08,812.06,Pago Mis Cuentas,2018-12-01,2019-01-01,0.0
201700,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37099,BAULERA Nº 3 - U.C. BI,...,01,2018,1,1,2018-04-16,78.96,Pago Mis Cuentas,2018-01-01,2018-02-01,1.0
201701,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37099,BAULERA Nº 3 - U.C. BI,...,02,2018,1,1,2018-04-16,84.35,Pago Mis Cuentas,2018-02-01,2018-03-01,1.0
201702,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37099,BAULERA Nº 3 - U.C. BI,...,03,2018,2,1,2018-04-16,65.76,Pago Mis Cuentas,2018-03-01,2018-04-01,0.0
201703,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37099,BAULERA Nº 3 - U.C. BI,...,04,2018,1,1,2018-05-04,70.55,Pago Mis Cuentas,2018-04-01,2018-05-01,0.0
201704,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37099,BAULERA Nº 3 - U.C. BI,...,05,2018,1,1,2018-06-05,67.21,Pago Mis Cuentas,2018-05-01,2018-06-01,0.0
201705,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37099,BAULERA Nº 3 - U.C. BI,...,06,2018,2,1,2018-07-05,82.07,Pago Mis Cuentas,2018-06-01,2018-07-01,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203719,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37248,BAULERA Nº 11 - U.C. AP,...,07,2018,1,1,2018-08-09,106.57,Link Pagos,2018-07-01,2018-08-01,0.0
203720,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37248,BAULERA Nº 11 - U.C. AP,...,08,2018,1,1,2018-09-05,126.89,Link Pagos,2018-08-01,2018-09-01,0.0
203721,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37248,BAULERA Nº 11 - U.C. AP,...,09,2018,1,1,2018-10-10,117.56,Link Pagos,2018-09-01,2018-10-01,0.0
203722,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37248,BAULERA Nº 11 - U.C. AP,...,10,2018,1,1,2018-11-09,119.69,Link Pagos,2018-10-01,2018-11-01,0.0
203723,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37248,BAULERA Nº 11 - U.C. AP,...,11,2018,1,1,2018-12-11,129.88,Pago Mis Cuentas,2018-11-01,2018-12-01,0.0
203724,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37248,BAULERA Nº 11 - U.C. AP,...,12,2018,1,1,2019-01-08,172.26,Link Pagos,2018-12-01,2019-01-01,0.0
203727,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37249,BAULERA Nº 12 - U.C. AQ,...,01,2018,1,1,2018-02-22,70.18,Rapipago,2018-01-01,2018-02-01,0.0
203728,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37249,BAULERA Nº 12 - U.C. AQ,...,02,2018,1,1,2018-03-09,78.46,Rapipago,2018-02-01,2018-03-01,0.0
203729,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37249,BAULERA Nº 12 - U.C. AQ,...,03,2018,2,1,2018-04-10,64.13,Rapipago,2018-03-01,2018-04-01,0.0
203730,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37249,BAULERA Nº 12 - U.C. AQ,...,04,2018,1,1,2018-05-09,70.55,Pago Facil,2018-04-01,2018-05-01,0.0
203731,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37249,BAULERA Nº 12 - U.C. AQ,...,05,2018,1,1,2018-06-13,67.21,Link Pagos,2018-05-01,2018-06-01,0.0
203732,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37249,BAULERA Nº 12 - U.C. AQ,...,06,2018,2,1,2018-07-10,82.07,Link Pagos,2018-06-01,2018-07-01,0.0
203733,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37249,BAULERA Nº 12 - U.C. AQ,...,07,2018,1,1,2018-08-09,76.12,Link Pagos,2018-07-01,2018-08-01,0.0
203734,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37249,BAULERA Nº 12 - U.C. AQ,...,08,2018,1,1,2018-09-05,90.64,Link Pagos,2018-08-01,2018-09-01,0.0
203735,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37249,BAULERA Nº 12 - U.C. AQ,...,09,2018,1,1,2018-10-10,83.97,Link Pagos,2018-09-01,2018-10-01,0.0
203736,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37249,BAULERA Nº 12 - U.C. AQ,...,10,2018,1,1,2018-11-09,85.50,Link Pagos,2018-10-01,2018-11-01,0.0
203737,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37249,BAULERA Nº 12 - U.C. AQ,...,11,2018,1,1,2018-12-11,92.77,Pago Mis Cuentas,2018-11-01,2018-12-01,0.0
203738,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37249,BAULERA Nº 12 - U.C. AQ,...,12,2018,1,1,2019-01-08,123.04,Link Pagos,2018-12-01,2019-01-01,0.0
203741,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37250,BAULERA Nº 13 - U.C. BG,...,01,2018,1,1,2018-02-22,68.34,Rapipago,2018-01-01,2018-02-01,0.0
203742,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37250,BAULERA Nº 13 - U.C. BG,...,02,2018,1,1,2018-03-09,62.78,Rapipago,2018-02-01,2018-03-01,0.0
203743,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37250,BAULERA Nº 13 - U.C. BG,...,03,2018,2,1,2018-04-10,51.32,Rapipago,2018-03-01,2018-04-01,0.0
203744,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37250,BAULERA Nº 13 - U.C. BG,...,04,2018,1,1,2018-05-08,56.44,Rapipago,2018-04-01,2018-05-01,0.0
203745,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37250,BAULERA Nº 13 - U.C. BG,...,05,2018,1,1,2018-06-13,53.77,Link Pagos,2018-05-01,2018-06-01,0.0
203746,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37250,BAULERA Nº 13 - U.C. BG,...,06,2018,2,1,2018-07-10,65.66,Link Pagos,2018-06-01,2018-07-01,0.0
203747,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37250,BAULERA Nº 13 - U.C. BG,...,07,2018,1,1,2018-08-09,60.90,Link Pagos,2018-07-01,2018-08-01,0.0
203748,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37250,BAULERA Nº 13 - U.C. BG,...,08,2018,1,1,2018-09-05,72.51,Link Pagos,2018-08-01,2018-09-01,0.0
203749,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37250,BAULERA Nº 13 - U.C. BG,...,09,2018,1,1,2018-10-10,67.18,Link Pagos,2018-09-01,2018-10-01,0.0
203750,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37250,BAULERA Nº 13 - U.C. BG,...,10,2018,1,1,2018-11-09,68.40,Link Pagos,2018-10-01,2018-11-01,0.0
203751,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37250,BAULERA Nº 13 - U.C. BG,...,11,2018,1,1,2018-12-11,74.22,Pago Mis Cuentas,2018-11-01,2018-12-01,0.0
203752,1715,2017-12-26 15:49:42,Consorcio Alysa I,mes_vencido,parcial,normal,False,False,37250,BAULERA Nº 13 - U.C. BG,...,12,2018,1,1,2019-01-08,98.43,Link Pagos,2018-12-01,2019-01-01,0.0