In [2]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

In [39]:
data = pd.read_csv("../../data/processed/data_2.csv",
                   dtype = {
                            "expensa_id": "object",
                            "unidad_id": "object",
                            "propietario_id": "object",
                            "inquilino_id": "object",
                            "consorcio_id": "object",
                            "expensa_padre_id": "object",
                            "unidad_prop": "object",
                            "consorcio_id": "object",
                            "usuario_creador_id": "object",
                            "concepto_id": "object",
                            "mes": "object",
                            "anio": "object",
                            "unidad_denominacion":"object",
                            "consorcio_nombre": "object",
                            "version":"object",
                            "concepto_id": "object",
                            "unidad_tipo": "object",
                            "modo_pago": "object",
                            "forma_prorrateo": "object",
                            "tipo_prorrateo": "object",
                            "metodo_pago": "object",    
                            "venc_1_dayofweek": "object",
                            "venc_2_dayofweek": "object",
                            "venc_1_dayofweek_ant": "object",
                            "venc_2_dayofweek_ant": "object",
                            "dia_inicio_mes_vencimiento": "object"
                    },
                    parse_dates = ["fecha_vencimiento_1", "fecha_vencimiento_2"])

data = data[['unidad_id', 'unidad_tipo', 'modo_pago', 'tamanio_consorcio',
             'fecha_expensa_x','mes_vencimiento','dia_inicio_mes_vencimiento',
             'fecha_vencimiento_1', 'venc_1_dayofweek', 'venc_1_day',
             'fecha_vencimiento_2', 'venc_2_dayofweek', 'venc_2_day',             
             'monto', 'monto_total', 'monto_parcial', 
             'int_dia', 'int_mes', 
             'cum_impago_ant', 'cum_pago_tardio_1_ant','cum_pago_tardio_2_ant',
             'mes',  
             'version',
             'metodo_pago',
             'impago', 'pago_tardio_1', 'pago_tardio_2',
             'fecha_expensa_anterior']]

data.columns = ['unidad_id', 'unidad_tipo', 'modo_pago', 'tamanio_consorcio',
                 'fecha_expensa','mes_vencimiento','dia_inicio_mes_vencimiento',
                 'fecha_vencimiento_1', 'fecha_vencimiento_1_dayofweek', 'fecha_vencimiento_1_daynumber',
                 'fecha_vencimiento_2', 'fecha_vencimiento_2_dayofweek', 'fecha_vencimiento_2_daynumber',             
                 'monto', 'monto_total', 'monto_parcial', 
                 'int_dia', 'int_mes', 
                 'cantidad_impagos_a_la_fecha', 'cantidad_pagos_tardios_1_a_la_fecha','cantidad_pagos_tardios_2_a_la_fecha',
                 'mes',  
                 'version',        
                 'metodo_pago',
                 'impago', 'pago_tardio_1', 'pago_tardio_2',
                 'fecha_expensa_anterior']

In [40]:
data["target"] = data["impago"].map(int).map(str) + data["pago_tardio_1"].map(int).map(str) +data["pago_tardio_2"].map(int).map(str)

In [41]:
data.loc[data.target == '000', "target"] = "A Tiempo"
data.loc[data.target == '100', "target"] = "Impago"
data.loc[data.target == '010', "target"] = "Tardio 1"
data.loc[data.target == '001', "target"] = "Tardio 2"

In [42]:
data = data.set_index(["unidad_id","fecha_expensa"])

In [43]:
data_mes_anterior = data[['metodo_pago']]

In [44]:
data = pd.merge(data,
         data_mes_anterior,
         left_on = ["unidad_id","fecha_expensa_anterior"],
         right_index = True,
         suffixes = ("", "_lag_1"))

In [45]:
data = data.reset_index()

In [157]:
data_unidad = data.loc[data.level_0 == "910", ['dia_inicio_mes_vencimiento', 'fecha_vencimiento_1_dayofweek', 'fecha_vencimiento_1_daynumber',
                'fecha_vencimiento_2_dayofweek', 'fecha_vencimiento_2_daynumber',             
                 'int_dia', 'int_mes', 
                 'cantidad_impagos_a_la_fecha', 'cantidad_pagos_tardios_1_a_la_fecha','cantidad_pagos_tardios_2_a_la_fecha',
                 'mes', 
                 'metodo_pago_lag_1',
                 'target']]

In [158]:
data_unidad.fecha_vencimiento_1_daynumber = data_unidad.fecha_vencimiento_1_daynumber.map(str)
data_unidad.fecha_vencimiento_2_daynumber = data_unidad.fecha_vencimiento_2_daynumber.map(str)

In [159]:
data_unidad = data_unidad.fillna(0)

In [160]:
data_unidad = pd.get_dummies(data_unidad)

In [161]:
data_unidad.shape

(59, 47)

In [163]:
data_unidad.iloc[:,[44,45,46]]

      target_A Tiempo  target_Impago  target_Tardio 1
8428                0              1                0
8429                0              0                1
8430                1              0                0
8431                0              0                1
8432                0              1                0
8433                1              0                0
8434                0              0                1
8435                1              0                0
8436                1              0                0
8437                1              0                0
8438                1              0                0
8439                1              0                0
8440                0              0                1
8441                1              0                0
8442                1              0                0
8443                0              1                0
8444                0              1                0
8445                0              1                0
8446                0              1                0
8447                0              1                0
8448                0              1                0
8449                0              1                0
8450                0              1                0
8451                0              1                0
8452                0              1                0
8453                0              1                0
8454                0              1                0
8455                0              1                0
8456                0              1                0
8457                0              1                0
8458                0              1                0
8459                0              1                0
8460                0              1                0
8461                0              1                0
8462                0              1                0
8463                0              1                0
8464                0              1                0
8465                0              1                0
8466                0              1                0
8467                0              1                0
8468                0              1                0
8469                0              1                0
8470                0              1                0
8471                0              1                0
8472                1              0                0
8473                1              0                0
8474                1              0                0
8475                0              0                1
8476                1              0                0
8477                0              0                1
8478                1              0                0
8479                1              0                0
8480                1              0                0
8481                1              0                0
8482                0              0                1
8483                1              0                0
8484                1              0                0
8485                1              0                0
8486                1              0                0

In [164]:
def build_timeseries(mat, n_clases, y_col_indexes):
    # y_col_index is the index of column that would act as output column
    # total number of time-series samples would be len(mat) - TIME_STEPS
    dim_0 = mat.shape[0] - TIME_STEPS
    dim_1 = mat.shape[1]
    x = np.zeros((dim_0, TIME_STEPS, dim_1))
    y = np.zeros((dim_0, n_clases))
    
    for i in range(dim_0):
        x[i] = mat[i:TIME_STEPS+i]
        for col_index in y_col_indexes:
            y[i, col_index - y_col_indexes[0]] = mat[TIME_STEPS+i, col_index]
    print("length of time-series i/o",x.shape,y.shape)
    return x, y

In [165]:
X,y = build_timeseries(data_unidad.values, 3, [44,45,46])

length of time-series i/o (53, 6, 47) (53, 3)

In [168]:
X_t = X[2:47,:,:]
y_t = y[2:47,:]
X_val = X[41:47,:,:]
y_val = y[41:47]
X_test = X[47:,:,:]
y_test = y[47:]

In [169]:
BATCH_SIZE = 3
TIME_STEPS = 6

In [2]:
from keras.layers.core import Dense, Dropout, Activation
from keras.models import Sequential
from keras.layers import LSTM

lstm_model = Sequential()
lstm_model.add(LSTM(100, batch_input_shape=(BATCH_SIZE, TIME_STEPS, X.shape[2]), dropout=0.0, recurrent_dropout=0.0, stateful=True, kernel_initializer='random_uniform'))
lstm_model.add(Dropout(0.5))
lstm_model.add(Dense(20,activation='relu'))
lstm_model.add(Dense(3,activation='sigmoid'))
lstm_model.compile(loss='categorical_crossentropy', optimizer="adam")

NameError: name 'X_train' is not defined

In [173]:
lstm_model.fit(X_t, y_t,  validation_data=(X_val, y_val), epochs=10, verbose=2, batch_size=BATCH_SIZE,
                    shuffle=False)

Train on 45 samples, validate on 6 samples
Epoch 1/10
 - 2s - loss: 1.0660 - val_loss: 1.3168
Epoch 2/10
 - 0s - loss: 0.9387 - val_loss: 1.5640
Epoch 3/10
 - 0s - loss: 0.8492 - val_loss: 1.5244
Epoch 4/10
 - 0s - loss: 0.8017 - val_loss: 1.5405
Epoch 5/10
 - 0s - loss: 0.8244 - val_loss: 1.6312
Epoch 6/10
 - 0s - loss: 0.7942 - val_loss: 1.4599
Epoch 7/10
 - 0s - loss: 0.7271 - val_loss: 1.3565
Epoch 8/10
 - 0s - loss: 0.7188 - val_loss: 1.3023
Epoch 9/10
 - 0s - loss: 0.5827 - val_loss: 1.2205
Epoch 10/10
 - 0s - loss: 0.5918 - val_loss: 1.1383

In [175]:
lstm_model.predict_classes(X_test,batch_size=3)

array([1, 1, 1, 1, 1, 1], dtype=int64)

In [176]:
y_test

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [120]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
confusion_matrix(y, lstm_model.predict(X))

ValueError: In a stateful network, you should only pass inputs with a number of samples that can be divided by the batch size. Found: 55 samples. Batch size: 32.

In [ ]:
print("accuracy",accuracy_score(Y_train, xgb.predict(X_train)))
print("precision",precision_score(Y_train, xgb.predict(X_train)))
print("recall",recall_score(Y_train, xgb.predict(X_train)))