In [11]:
import pandas as pd
import numpy as np
from plotnine import *

%matplotlib inline

In [42]:
pd.set_option('display.max_rows', 200)

In [17]:
data = pd.read_csv("../../data/processed/expensas_full.csv",
                  dtype = {
                                "expensa_id": "object",
                                "unidad_id": "object",
                                "propietario_id": "object",
                                "inquilino_id": "object",
                                "consorcio_id": "object",
                                "consorcio_usa_fondo": "bool",
                                "consorcio_solo_muestra_cat": "bool",
                                "unidad_tipo":"object",
                                "expensa_concepto": "object",
                                "expensa_mes":"object",
                                "expensa_anio":"object",
                                "unidad_propietario":"object",
                                "unidad_inquilino":"object",
                                "expensa_version":"object"
                            })

In [18]:
data.describe()

,consorcio_interes_primer_vencimiento,consorcio_interes_segundo_vencimiento,unidad_metros,expensa_monto,expensa_monto_total,expensa_monto_parcial,epensa_proporcion,expensa_saldo_utilizado,expensa_descuento,expensa_interes_primer_vencimiento,expensa_ineteres_segundo_vencimiento,pago_monto
count,276684.000000,276684.000000,276684.000000,276684.000000,2.766840e+05,276682.000000,276255.000000,276684.0,276684.0,276684.00000,276684.000000,237191.000000
mean,3.585484,5.471743,16.675639,1883.735529,2.568232e+05,32.225806,4.964487,0.0,0.0,3.43292,5.308268,1941.933403
std,3.082874,3.138934,253.107055,2008.307947,3.898618e+05,417.262081,17.430235,0.0,0.0,2.98482,3.036037,2545.859180
min,0.000000,0.000000,0.000000,-3091.000000,-4.827630e+03,-3091.000000,-141.583551,0.0,0.0,0.00000,0.000000,-3091.000000
25%,2.000000,3.750000,0.547000,727.290000,4.450000e+04,0.000000,0.401000,0.0,0.0,2.00000,3.750000,775.000000
50%,3.000000,5.000000,1.450000,1470.560000,1.127564e+05,0.000000,1.469841,0.0,0.0,3.00000,5.000000,1542.450000
75%,5.000000,6.000000,3.570000,2520.205000,2.650006e+05,0.000000,3.124548,0.0,0.0,5.00000,6.000000,2600.830000
max,35.000000,35.000000,11111.000000,158025.190000,3.946655e+06,43039.230000,2915.881126,0.0,0.0,35.00000,35.000000,484620.000000

In [108]:
temp = data.loc[(data.epensa_proporcion >= 85) & (data.epensa_proporcion<98),["expensa_id","consorcio_id","consorcio_nombre","unidad_denominacion", "expensa_mes", "expensa_anio", "expensa_monto", "expensa_monto_total", "epensa_proporcion", "expensa_concepto", "pago_monto"]]
temp.expensa_mes = temp.expensa_mes.map(int)
temp.sort_values(["consorcio_nombre", "unidad_denominacion","expensa_anio", "expensa_mes"])

,expensa_id,consorcio_id,consorcio_nombre,unidad_denominacion,expensa_mes,expensa_anio,expensa_monto,expensa_monto_total,epensa_proporcion,expensa_concepto,pago_monto
236850,209678,1748,CONSORCIO EDIFICIO CAMPUS\t,"PH 38 - 6° PISO D""""",11,2017,3272.00,3386.00,96.633196,1,3436.00
236851,209680,1748,CONSORCIO EDIFICIO CAMPUS\t,"PH 38 - 6° PISO D""""",12,2017,3272.00,3386.00,96.633196,1,3403.00
169609,131302,1621,CONSORCIO INARCO 20,4º-F,2,2016,2501.26,2728.65,91.666575,1,4327.34
169610,131384,1621,CONSORCIO INARCO 20,4º-F,3,2016,2463.87,2687.86,91.666605,1,4147.44
169611,131464,1621,CONSORCIO INARCO 20,4º-F,4,2016,3681.67,4016.37,91.666604,1,6025.23
169612,131544,1621,CONSORCIO INARCO 20,4º-F,5,2016,2959.32,3228.35,91.666641,1,4704.69
169625,136366,1621,CONSORCIO INARCO 20,4º-F,6,2016,2545.32,2776.71,91.666757,1,3927.50
169613,131704,1621,CONSORCIO INARCO 20,4º-F,7,2016,3115.67,3398.91,91.666740,1,4661.89
169614,131784,1621,CONSORCIO INARCO 20,4º-F,8,2016,3194.58,3485.00,91.666571,1,4630.59
181789,131202,1631,CONSORCIO INARCO 29,1º-H,6,2017,5277.54,5904.10,89.387714,1,5870.74
275494,413558,2053,Consorcio de Propietarios Marco Polo 5345,UF 24 - DEPTO 24,12,2018,4191.88,4310.00,97.259397,1,4192.00
263932,382257,1887,EDIFICIO LIMA 135,3F,3,2017,33261.00,34858.00,95.418555,1,53717.00
263816,382269,1887,EDIFICIO LIMA 135,PB C,11,2017,3425.00,3973.00,86.206897,1,4709.00

In [50]:
temp.loc[temp2.consorcio_id=="1533",:].sort_values(["consorcio_nombre", "unidad_denominacion","expensa_anio", "expensa_mes"])

,expensa_id,consorcio_id,consorcio_nombre,unidad_denominacion,expensa_mes,expensa_anio,expensa_monto,expensa_monto_total,epensa_proporcion,expensa_concepto,monto_pago
125906,82011,1533,Pontevea,4 C - PH 26,10,2012,328.60,271.2,121.165192,1,NaN
125911,82017,1533,Pontevea,4 C - PH 26,4,2013,414.00,306.0,135.294118,1,NaN
125912,82018,1533,Pontevea,4 C - PH 26,5,2013,467.71,306.0,152.846405,1,NaN
125913,82019,1533,Pontevea,4 C - PH 26,6,2013,414.00,306.0,135.294118,1,NaN
125914,82020,1533,Pontevea,4 C - PH 26,7,2013,414.00,306.0,135.294118,1,NaN
125915,82021,1533,Pontevea,4 C - PH 26,8,2013,414.00,306.0,135.294118,1,NaN
125916,82022,1533,Pontevea,4 C - PH 26,9,2013,414.00,306.0,135.294118,1,NaN
125920,82026,1533,Pontevea,4 C - PH 26,2,2014,478.60,375.6,127.422790,1,NaN
125921,82027,1533,Pontevea,4 C - PH 26,3,2014,472.70,375.6,125.851970,1,NaN
125922,82028,1533,Pontevea,4 C - PH 26,4,2014,1217.60,375.6,324.174654,1,NaN
125926,82032,1533,Pontevea,4 C - PH 26,8,2014,603.10,375.6,160.569755,1,NaN
125928,82034,1533,Pontevea,4 C - PH 26,10,2014,607.70,506.3,120.027652,1,NaN
125929,82035,1533,Pontevea,4 C - PH 26,11,2014,746.80,506.3,147.501481,1,NaN
125933,82039,1533,Pontevea,4 C - PH 26,4,2015,574.90,506.3,113.549279,1,NaN
125934,82040,1533,Pontevea,4 C - PH 26,5,2015,599.20,536.9,111.603651,1,NaN
125935,82041,1533,Pontevea,4 C - PH 26,6,2015,599.20,536.9,111.603651,1,NaN
125937,82043,1533,Pontevea,4 C - PH 26,8,2015,710.90,639.9,111.095484,1,NaN
125938,82044,1533,Pontevea,4 C - PH 26,9,2015,710.90,639.9,111.095484,1,NaN
125939,82045,1533,Pontevea,4 C - PH 26,10,2015,874.20,653.8,133.710615,1,NaN
125940,82046,1533,Pontevea,4 C - PH 26,11,2015,672.60,653.8,102.875497,1,NaN
125942,82048,1533,Pontevea,4 C - PH 26,2,2016,772.70,686.5,112.556446,1,NaN
125944,82050,1533,Pontevea,4 C - PH 26,4,2016,779.70,747.0,104.377510,1,NaN
125945,82051,1533,Pontevea,4 C - PH 26,5,2016,981.70,792.9,123.811326,1,NaN
125946,82052,1533,Pontevea,4 C - PH 26,6,2016,970.00,792.9,122.335730,1,NaN
125947,82053,1533,Pontevea,4 C - PH 26,7,2016,863.90,792.9,108.954471,1,NaN
125948,82054,1533,Pontevea,4 C - PH 26,8,2016,941.80,870.8,108.153422,1,NaN
125949,82055,1533,Pontevea,4 C - PH 26,9,2016,1113.10,870.8,127.824989,1,NaN

In [67]:
temp.groupby(["consorcio_id","consorcio_nombre"]).count()

,,expensa_id,unidad_denominacion,expensa_mes,expensa_anio,expensa_monto,expensa_monto_total,epensa_proporcion,expensa_concepto,monto_pago
consorcio_id,consorcio_nombre,,,,,,,,,
1410,EDIFICIO CALICANTO,26,26,26,26,26,26,26,26,0
1421,TORRE PRIVATO,5,5,5,5,5,5,5,5,0
1422,PARQUE PRIVATO,11,11,11,11,11,11,11,11,0
1423,PLAZA PRIVATO,8,8,8,8,8,8,8,8,0
1425,JARDIN PRIVATO,13,13,13,13,13,13,13,13,0
1427,RONDEAU PRIVATO,6,6,6,6,6,6,6,6,0
1429,PEREDO PRIVATO,10,10,10,10,10,10,10,10,0
1431,EDIFICIO ARVIAL,7,7,7,7,7,7,7,7,0
1445,EL NOGAL,2,2,2,2,2,2,2,2,0
1446,CONSROCIO LACOSTA 230,2,2,2,2,2,2,2,2,0
1496,Consorcio Edificio RIO II,2,2,2,2,2,2,2,2,0
1517,Consorcio Edificio ECOR PLAZA II,38,38,38,38,38,38,38,38,0
1528,MARIA REINA I,1,1,1,1,1,1,1,1,0
1533,Pontevea,52,52,52,52,52,52,52,52,0
1535,Consorcio Colombia 69,2,2,2,2,2,2,2,2,0
1539,Consorcio Santa Rosa,8,8,8,8,8,8,8,8,0
1540,Astral Histórico,39,39,39,39,39,39,39,39,0
1541,Consorcio Artigas,16,16,16,16,16,16,16,16,0
1542,Consorcio Obispo Trejo,3,3,3,3,3,3,3,3,0
1543,Consorcio Iris II,4,4,4,4,4,4,4,4,0
1544,Consorcio Dean Funes,2,2,2,2,2,2,2,2,0
1547,Consorcio Edificio EL MAITEN,93,93,93,93,93,93,93,93,0
1549,CUÑATAI BARRIO PRIVADO,1,1,1,1,1,1,1,1,0
1564,Consorcio GALERIA ALTO VALLE,18,18,18,18,18,18,18,18,0
1584,Florida XXV,1,1,1,1,1,1,1,1,0
1585,Consorcio Edificio ATLAS IV,2,2,2,2,2,2,2,2,0
1596,Consorcio Edificio ATLAS I,24,24,24,24,24,24,24,24,0
1597,Consorcio Edificio VILLEGAS,26,26,26,26,26,26,26,26,0
1598,Tejas Dos,382,382,382,382,382,382,382,382,0
1606,Consorcio Edificio LA BARRA I,36,36,36,36,36,36,36,36,0
1607,Consorcio GALERIA HIPOCAMPPUS,31,31,31,31,31,31,31,31,0
1618,Jardin Claret,122,122,122,122,122,122,122,122,0
1622,CONSORCIO INARCO 21,6,6,6,6,6,6,6,6,0
1623,CONSORCIO INARCO 22,2,2,2,2,2,2,2,2,0
1626,CONSORCIO INARCO 25,1,1,1,1,1,1,1,1,0
1629,CONSORCIO INARCO 27,3,3,3,3,3,3,3,3,0
1630,CONSORCIO INARCO 28,2,2,2,2,2,2,2,2,0
1632,Consorcio INARCO OFFICE,1,1,1,1,1,1,1,1,0
1634,Barcelona Capuchinos,7,7,7,7,7,7,7,7,0
1635,Buen Ayre,43,43,43,43,43,43,43,43,0
1636,Terrazas del Palacio,21,21,21,21,21,21,21,21,0
1639,PLAZA COLON,1,1,1,1,1,1,1,1,0
1644,Portofino I,4,4,4,4,4,4,4,4,0
1648,Altos Y Bosques de Catalina,2718,2718,2718,2718,2718,2718,2718,2718,0
1666,EDIFICIO CUYO II,9,9,9,9,9,9,9,9,0
1668,9 de julio 1345,32,32,32,32,32,32,32,32,0
1672,Tejas del Sur Cuatro SA,168,168,168,168,168,168,168,168,0
1679,Callao 1659,1,1,1,1,1,1,1,1,0
1682,Crespo 1476,1,1,1,1,1,1,1,1,0
1686,Los Ciervos,16,16,16,16,16,16,16,16,0
1687,Los Cedros,3,3,3,3,3,3,3,3,0
1688,Sol de Mayo,10,10,10,10,10,10,10,10,0
1689,Larrañaga Office,16,16,16,16,16,16,16,16,0
1690,Gran Estrada III,86,86,86,86,86,86,86,86,0
1695,Puente Blanco,44,44,44,44,44,44,44,44,0
1697,ELIO VI,1,1,1,1,1,1,1,1,0
1700,MAIPÚ Nº 181,2,2,2,2,2,2,2,2,0
1701,Consorcio Alto Pia,3,3,3,3,3,3,3,3,0
1702,Opera Ficticio,2,2,2,2,2,2,2,2,0
1719,HAROLD I,25,25,25,25,25,25,25,25,0
1720,TORRE SALGUERO,7,7,7,7,7,7,7,7,0
1721,TUCUMAN 38,4,4,4,4,4,4,4,4,0
1730,Consorcio Silfer 1,6,6,6,6,6,6,6,6,0
1749,Consorcio Idaniko,13,13,13,13,13,13,13,13,0
1750,Sierra Nueva,498,498,498,498,498,498,498,498,0
1757,LA CERCANIA - BARRIO CERRADO,1,1,1,1,1,1,1,1,0
1759,Consorcio Prueba Envios Emails,1,1,1,1,1,1,1,1,0
1761,Consorcio Fiumiccino VI,1,1,1,1,1,1,1,1,0
1772,Complejo de Unidades Demo,1,1,1,1,1,1,1,1,0
1779,CORRIENTES 2875,6,6,6,6,6,6,6,6,0
1789,PANADERIA ESPERANZA,25,25,25,25,25,25,25,25,0
1790,NEÓN I,13,13,13,13,13,13,13,13,0
1792,NOELIA I,24,24,24,24,24,24,24,24,0
1796,El Sol S.A.I.C. y .F.,606,606,606,606,606,606,606,606,0
1816,Edificio TORRE VARELA II,1,1,1,1,1,1,1,1,0
1818,Consorcio Edificio Nueva Cordoba,20,20,20,20,20,20,20,20,0
1821,CONSORCIO AYACUCHO,16,16,16,16,16,16,16,16,0
1846,CONSORCIO MARIANA I,1,1,1,1,1,1,1,1,0
1848,Consorcio Andrea Palladio Extraordinarias,12,12,12,12,12,12,12,12,0
1850,CONSORCIO CENTRAL,13,13,13,13,13,13,13,13,0
1851,CONSORCIO DEMOR IV,21,21,21,21,21,21,21,21,0
1852,CONSORCIO EUROPA IX,18,18,18,18,18,18,18,18,0
1853,CONSORCIO NIROMAR II,64,64,64,64,64,64,64,64,0
1854,CONSORCIO DEMOR VIII,17,17,17,17,17,17,17,17,0
1855,CONSORCIO DELFINA V,12,12,12,12,12,12,12,12,0
1856,CONSORCIO DELFINA VI,8,8,8,8,8,8,8,8,0
1857,CONSORCIO GRAN RIVIERA,18,18,18,18,18,18,18,18,0
1860,Consorcio Perú 131,22,22,22,22,22,22,22,22,0
1882,Consorcio 30 de Octubre,1,1,1,1,1,1,1,1,0
1884,CONSORCIO DE PROPIETARIOS BARRIO PRIVADO VALLE PARRAL,3,3,3,3,3,3,3,3,0
1887,EDIFICIO LIMA 135,7,7,7,7,7,7,7,7,0
1892,EDIFICIO EMILIO MUSICANT,1,1,1,1,1,1,1,1,0
1897,PROPIETARIOS EMILIO MUSICANT,1,1,1,1,1,1,1,1,0
1905,SANTA ANNA,1,1,1,1,1,1,1,1,0
1908,TORRE UNO/60,10,10,10,10,10,10,10,10,0
1919,Natania 50,405,405,405,405,405,405,405,405,0
1959,Consorcio 25 de mayo 1972,7,7,7,7,7,7,7,7,0
1960,Edificio Parque Garay Torre B,410,410,410,410,410,410,410,410,0
1961,LAGO,3,3,3,3,3,3,3,3,0
1963,General Lopez 2960,9,9,9,9,9,9,9,9,0
1965,SUR I,2,2,2,2,2,2,2,2,0
1968,SAN JERONIMO II,44,44,44,44,44,44,44,44,0
1974,OGARO II,10,10,10,10,10,10,10,10,0
1975,JUAN DEL CAMPILLO,7,7,7,7,7,7,7,7,0
1977,1 JUNTA 3422,10,10,10,10,10,10,10,10,0
1979,URQUIZA 1591,21,21,21,21,21,21,21,21,0
1981,LISANDRO DE LA TORRE Y 9 DE JULIO,94,94,94,94,94,94,94,94,0
1982,CATAMARCA 3528/30,13,13,13,13,13,13,13,13,0
1988,9 de julio 1233,3,3,3,3,3,3,3,3,0
1989,LEAN I,4,4,4,4,4,4,4,4,0
1990,OGARO I,26,26,26,26,26,26,26,26,0
1991,PILAR DE CATAMARCA,3,3,3,3,3,3,3,3,0
2005,LEGISLATURA,57,57,57,57,57,57,57,57,0
2006,CAUDILLOS V,173,173,173,173,173,173,173,173,0
2007,CELESTINO I,1,1,1,1,1,1,1,1,0
2015,Consorcio Astral III,4,4,4,4,4,4,4,4,0
2018,VILLA PRIVADA SAN ALFONSO I,327,327,327,327,327,327,327,327,0
2021,Inquilinos,43,43,43,43,43,43,43,43,0
2025,Consorcio Ustica,44,44,44,44,44,44,44,44,0
2040,CATAMARCA,1,1,1,1,1,1,1,1,0
2045,CONSORCIO EDIF CALLE A. GARZON 2662,4,4,4,4,4,4,4,4,0
2050,Consorcio de Propietarios Av. Gaona 1966,24,24,24,24,24,24,24,24,0
2051,Consorcio de Propietarios Crisólogo Larralde 3407 - Conde 3620,14,14,14,14,14,14,14,14,0
2052,Consorcio de Propietarios Heredia 1265,8,8,8,8,8,8,8,8,0
2053,Consorcio de Propietarios Marco Polo 5345,28,28,28,28,28,28,28,28,0
2054,Consorcio de Propietarios Palpa 2434,13,13,13,13,13,13,13,13,0
2055,Consorcio de Propietarios Teodoro Garcia 2425,27,27,27,27,27,27,27,27,0
2056,Consorcio de Propietarios ZADO 3334-36,14,14,14,14,14,14,14,14,0
2057,Consorcio de Propietarios Yerua 4955,1,1,1,1,1,1,1,1,0
2071,Edificio Macro 1,23,23,23,23,23,23,23,23,0
2086,Consorcio Calle 27 Nº 627,81,81,81,81,81,81,81,81,0
2092,PORTICA III,10,10,10,10,10,10,10,10,0
2093,PORTICA V,7,7,7,7,7,7,7,7,0
2094,PORTICA VI,4,4,4,4,4,4,4,4,0
2099,Consorcio Sicilia,96,96,96,96,96,96,96,96,0
533,Paso de los Andes,1,1,1,1,1,1,1,1,0
728,HOSTAL DEL SOL,4,4,4,4,4,4,4,4,0

In [75]:
pontevesa = data.loc[(data.consorcio_id=="1533"),:]
pontevesa.expensa_mes = pontevesa.expensa_mes.map(int)
pontevesa.groupby(["expensa_anio", "expensa_mes"]).count()

C:\Anaconda3\lib\site-packages\pandas\core\generic.py:5096: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

                          consorcio_id  consorcio_nombre  \
expensa_anio expensa_mes
2012         6                       1                 1
             7                       1                 1
             8                       1                 1
             9                       1                 1
             10                      1                 1
             11                      1                 1
             12                      1                 1
2013         1                       1                 1
             2                       1                 1
             3                       1                 1
             4                       1                 1
             5                       1                 1
             6                       1                 1
             7                       1                 1
             8                       1                 1
             9                       1                 1
             10                      1                 1
             11                      1                 1
             12                      1                 1
2014         1                       1                 1
             2                       1                 1
             3                       1                 1
             4                       1                 1
             5                       1                 1
             6                       1                 1
             7                       1                 1
             8                       1                 1
             9                       1                 1
             10                      1                 1
             11                      1                 1
             12                      1                 1
2015         1                       1                 1
             2                       4                 4
             3                       1                 1
             4                       1                 1
             5                       1                 1
             6                       1                 1
             7                       1                 1
             8                       2                 2
             9                       4                 4
             10                      4                 4
             11                      4                 4
             12                      4                 4
2016         1                       4                 4
             2                       6                 6
             3                       4                 4
             4                       4                 4
             5                       4                 4
             6                       5                 5
             7                       5                 5
             8                       8                 8
             9                      16                16
             10                     51                51
             11                     51                51
             12                     51                51
2017         1                      52                52
             2                      53                53
             3                      51                51
             4                      51                51
             5                      51                51
             6                      51                51
             7                      51                51
             8                      51                51
             9                      51                51
             10                     51                51
             11                     51                51
             12                     50                50
2018         1                      51                51
             2                      51                51
             3                      51                51
             4                      51                51
             5                      51                51
             6                      51                51
             7                      51                51
             8                      51                51
             9                      51                51
             10                     51                51
             11                     51                51
             12                     51                51
2019         1                      51                51
             2                      51                51
             3                      51                51

                          consorcio_interes_primer_vencimiento  \
expensa_anio expensa_mes
2012         6                                               1
             7                                               1
             8                                               1
             9                                               1
             10                                              1
             11                                              1
             12                                              1
2013         1                                               1
             2                                               1
             3                                               1
             4                                               1
             5                                               1
             6                                               1
             7                                               1
             8                                               1
             9                                               1
             10                                              1
             11                                              1
             12                                              1
2014         1                                               1
             2                                               1
             3                                               1
             4                                               1
             5                                               1
             6                                               1
             7                                               1
             8                                               1
             9                                               1
             10                                              1
             11                                              1
             12                                              1
2015         1                                               1
             2                                               4
             3                                               1
             4                                               1
             5                                               1
             6                                               1
             7                                               1
             8                                               2
             9                                               4
             10                                              4
             11                                              4
             12                                              4
2016         1                                               4
             2                                               6
             3                                               4
             4                                               4
             5                                               4
             6                                               5
             7                                               5
             8                                               8
             9                                              16
             10                                             51
             11                                             51
             12                                             51
2017         1                                              52
             2                                              53
             3                                              51
             4                                              51
             5                                              51
             6                                              51
             7                                              51
             8                                              51
             9                                              51
             10                                             51
             11                                             51
             12                                             50
2018         1                                              51
             2                                              51
             3                                              51
             4                                              51
             5                                              51
             6                                              51
             7                                              51
             8                                              51
             9                                              51
             10                                             51
             11                                             51
             12                                             51
2019         1                                              51
             2                                              51
             3                                              51

                          consorcio_interes_segundo_vencimiento  \
expensa_anio expensa_mes
2012         6                                                1
             7                                                1
             8                                                1
             9                                                1
             10                                               1
             11                                               1
             12                                               1
2013         1                                                1
             2                                                1
             3                                                1
             4                                                1
             5                                                1
             6                                                1
             7                                                1
             8                                                1
             9                                                1
             10                                               1
             11                                               1
             12                                               1
2014         1                                                1
             2                                                1
             3                                                1
             4                                                1
             5                                                1
             6                                                1
             7                                                1
             8                                                1
             9                                                1
             10                                               1
             11                                               1
             12                                               1
2015         1                                                1
             2                                                4
             3                                                1
             4                                                1
             5                                                1
             6                                                1
             7                                                1
             8                                                2
             9                                                4
             10                                               4
             11                                               4
             12                                               4
2016         1                                                4
             2                                                6
             3                                                4
             4                                                4
             5                                                4
             6                                                5
             7                                                5
             8                                                8
             9                                               16
             10                                              51
             11                                              51
             12                                              51
2017         1                                               52
             2                                               53
             3                                               51
             4                                               51
             5                                               51
             6                                               51
             7                                               51
             8                                               51
             9                                               51
             10                                              51
             11                                              51
             12                                              50
2018         1                                               51
             2                                               51
             3                                               51
             4                                               51
             5                                               51
             6                                               51
             7                                               51
             8                                               51
             9                                               51
             10                                              51
             11                                              51
             12                                              51
2019         1                                               51
             2                                               51
             3                                               51

                          consorcio_modo_pago  consorcio_visibilidad_gasto  \
expensa_anio expensa_mes
2012         6                              1                            1
             7                              1                            1
             8                              1                            1
             9                              1                            1
             10                             1                            1
             11                             1                            1
             12                             1                            1
2013         1                              1                            1
             2                              1                            1
             3                              1                            1
             4                              1                            1
             5                              1                            1
             6                              1                            1
             7                              1                            1
             8                              1                            1
             9                              1                            1
             10                             1                            1
             11                             1                            1
             12                             1                            1
2014         1                              1                            1
             2                              1                            1
             3                              1                            1
             4                              1                            1
             5                              1                            1
             6                              1                            1
             7                              1                            1
             8                              1                            1
             9                              1                            1
             10                             1                            1
             11                             1                            1
             12                             1                            1
2015         1                              1                            1
             2                              4                            4
             3                              1                            1
             4                              1                            1
             5                              1                            1
             6                              1                            1
             7                              1                            1
             8                              2                            2
             9                              4                            4
             10                             4                            4
             11                             4                            4
             12                             4                            4
2016         1                              4                            4
             2                              6                            6
             3                              4                            4
             4                              4                            4
             5                              4                            4
             6                              5                            5
             7                              5                            5
             8                              8                            8
             9                             16                           16
             10                            51                           51
             11                            51                           51
             12                            51                           51
2017         1                             52                           52
             2                             53                           53
             3                             51                           51
             4                             51                           51
             5                             51                           51

In [91]:
pontevesa.loc[(pontevesa.expensa_anio == "2015"), ["expensa_id","unidad_denominacion", "expensa_mes", "expensa_anio", "expensa_monto", "expensa_monto_total", "epensa_proporcion", "expensa_concepto", "pago_monto"]].sort_values(["expensa_anio","expensa_mes"])

,expensa_id,unidad_denominacion,expensa_mes,expensa_anio,expensa_monto,expensa_monto_total,epensa_proporcion,expensa_concepto,pago_monto
125930,82036,4 C - PH 26,1,2015,506.30,506.3,100.000000,1,NaN
125237,73689,1 A - PH 5,2,2015,3034.80,0.0,NaN,1,8679.53
125281,73702,1 B - PH 6,2,2015,3102.70,0.0,NaN,1,8873.72
125931,82037,4 C - PH 26,2,2015,506.30,506.3,100.000000,1,NaN
126658,73782,7 C - PH 49,2,2015,882.20,0.0,NaN,1,NaN
125932,82038,4 C - PH 26,3,2015,506.30,506.3,100.000000,1,NaN
125933,82039,4 C - PH 26,4,2015,574.90,506.3,113.549279,1,NaN
125934,82040,4 C - PH 26,5,2015,599.20,536.9,111.603651,1,NaN
125935,82041,4 C - PH 26,6,2015,599.20,536.9,111.603651,1,NaN
125936,82042,4 C - PH 26,7,2015,569.20,569.2,100.000000,1,NaN
125937,82043,4 C - PH 26,8,2015,710.90,639.9,111.095484,1,NaN
126654,73778,7 C - PH 49,8,2015,22.41,0.0,NaN,1,NaN
125234,73686,1 A - PH 5,9,2015,2332.60,0.0,NaN,1,3701.29
125278,73699,1 B - PH 6,9,2015,2386.20,0.0,NaN,1,3701.29
125938,82044,4 C - PH 26,9,2015,710.90,639.9,111.095484,1,NaN
126655,73779,7 C - PH 49,9,2015,14.22,0.0,NaN,1,NaN
125235,73687,1 A - PH 5,10,2015,2868.30,0.0,NaN,1,4416.81
125279,73700,1 B - PH 6,10,2015,2935.50,0.0,NaN,1,4418.37
125939,82045,4 C - PH 26,10,2015,874.20,653.8,133.710615,1,NaN
126656,73780,7 C - PH 49,10,2015,874.20,0.0,NaN,1,NaN
125236,73688,1 A - PH 5,11,2015,2207.30,0.0,NaN,1,3294.20
125280,73701,1 B - PH 6,11,2015,2258.70,0.0,NaN,1,3295.77
125940,82046,4 C - PH 26,11,2015,672.60,653.8,102.875497,1,NaN
126657,73781,7 C - PH 49,11,2015,672.60,0.0,NaN,1,NaN
125247,76321,1 A - PH 5,12,2015,3034.80,0.0,NaN,1,4244.58
125291,76322,1 B - PH 6,12,2015,3102.70,0.0,NaN,1,4241.45
125901,76326,4 C - PH 26,12,2015,882.20,882.2,100.000000,1,NaN
126668,76328,7 C - PH 49,12,2015,0.00,0.0,NaN,1,0.00

In [74]:
altosybosques = data.loc[(data.consorcio_id=="1648"),:]
altosybosques.expensa_mes = altosybosques.expensa_mes.map(int)
altosybosques.groupby(["expensa_anio", "expensa_mes"]).count()

C:\Anaconda3\lib\site-packages\pandas\core\generic.py:5096: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

                          consorcio_id  consorcio_nombre  \
expensa_anio expensa_mes
2015         1                      48                48
             2                      51                51
             3                      51                51
             4                      56                56
             5                      56                56
             6                      61                61
             7                      66                66
             8                      68                68
             9                      70                70
             10                     70                70
             11                     71                71
             12                     74                74
2016         1                      76                76
             2                      77                77
             3                      77                77
             4                      78                78
             5                      80                80
             6                      86                86
             7                      87                87
             8                      86                86
             9                      88                88
             10                     88                88
             11                     93                93
             12                     97                97
2017         1                     102               102
             2                     108               108
             3                     110               110
             4                     110               110
             5                     112               112
             6                     114               114
             7                     123               123
             8                     174               174
             9                     367               367
             10                    368               368
             11                    368               368
             12                    368               368
2018         1                     369               369
             2                     367               367
             3                     368               368
             4                     368               368
             5                     369               369
             6                     368               368
             7                     370               370
             8                     370               370
             9                     373               373
             10                    374               374
             11                    374               374
             12                    374               374
2019         1                     374               374
             2                     375               375
             3                     375               375

                          consorcio_interes_primer_vencimiento  \
expensa_anio expensa_mes
2015         1                                              48
             2                                              51
             3                                              51
             4                                              56
             5                                              56
             6                                              61
             7                                              66
             8                                              68
             9                                              70
             10                                             70
             11                                             71
             12                                             74
2016         1                                              76
             2                                              77
             3                                              77
             4                                              78
             5                                              80
             6                                              86
             7                                              87
             8                                              86
             9                                              88
             10                                             88
             11                                             93
             12                                             97
2017         1                                             102
             2                                             108
             3                                             110
             4                                             110
             5                                             112
             6                                             114
             7                                             123
             8                                             174
             9                                             367
             10                                            368
             11                                            368
             12                                            368
2018         1                                             369
             2                                             367
             3                                             368
             4                                             368
             5                                             369
             6                                             368
             7                                             370
             8                                             370
             9                                             373
             10                                            374
             11                                            374
             12                                            374
2019         1                                             374
             2                                             375
             3                                             375

                          consorcio_interes_segundo_vencimiento  \
expensa_anio expensa_mes
2015         1                                               48
             2                                               51
             3                                               51
             4                                               56
             5                                               56
             6                                               61
             7                                               66
             8                                               68
             9                                               70
             10                                              70
             11                                              71
             12                                              74
2016         1                                               76
             2                                               77
             3                                               77
             4                                               78
             5                                               80
             6                                               86
             7                                               87
             8                                               86
             9                                               88
             10                                              88
             11                                              93
             12                                              97
2017         1                                              102
             2                                              108
             3                                              110
             4                                              110
             5                                              112
             6                                              114
             7                                              123
             8                                              174
             9                                              367
             10                                             368
             11                                             368
             12                                             368
2018         1                                              369
             2                                              367
             3                                              368
             4                                              368
             5                                              369
             6                                              368
             7                                              370
             8                                              370
             9                                              373
             10                                             374
             11                                             374
             12                                             374
2019         1                                              374
             2                                              375
             3                                              375

                          consorcio_modo_pago  consorcio_visibilidad_gasto  \
expensa_anio expensa_mes
2015         1                             48                           48
             2                             51                           51
             3                             51                           51
             4                             56                           56
             5                             56                           56
             6                             61                           61
             7                             66                           66
             8                             68                           68
             9                             70                           70
             10                            70                           70
             11                            71                           71
             12                            74                           74
2016         1                             76                           76
             2                             77                           77
             3                             77                           77
             4                             78                           78
             5                             80                           80
             6                             86                           86
             7                             87                           87
             8                             86                           86
             9                             88                           88
             10                            88                           88
             11                            93                           93
             12                            97                           97
2017         1                            102                          102
             2                            108                          108
             3                            110                          110
             4                            110                          110
             5                            112                          112
             6                            114                          114
             7                            123                          123
             8                            174                          174
             9                            367                          367
             10                           368                          368
             11                           368                          368
             12                           368                          368
2018         1                            369                          369
             2                            367                          367
             3                            368                          368
             4                            368                          368
             5                            369                          369
             6                            368                          368
             7                            370                          370
             8                            370                          370
             9                            373                          373
             10                           374                          374
             11                           374                          374
             12                           374                          374
2019         1                            374                          374
             2                            375                          375
             3                            375                          375

                          consorcio_tipo  consorcio_usa_fondo  \
expensa_anio expensa_mes
2015         1                        48                   48
             2                        51                   51
             3                        51                   51
             4                        56                   56
             5                        56                   56
             6                        61                   61
             7                        66                   66
             8                        68                   68
             9                        70                   70
             10                       70                   70
             11                       71                   71
             12                       74                   74
2016         1                        76                   76
             2                        77                   77
             3                        77                   77
             4                        78                   78
             5                        80                   80
             6                        86                   86
             7                        87                   87
             8                        86                   86
             9                        88                   88
             10                       88                   88
             11                       93                   93
             12                       97                   97
2017         1                       102                  102
             2                       108                  108
             3                       110                  110
             4                       110                  110
             5                       112                  112
             6                       114                  114
             7                       123                  123
             8                       174                  174
             9                       367                  367
             10                      368                  368
             11                      368                  368
             12                      368                  368
2018         1                       369                  369
             2                       367                  367
             3                       368                  368
             4                       368                  368
             5                       369                  369
             6                       368                  368
             7                       370                  370
             8                       370                  370
             9                       373                  373
             10                      374                  374
             11                      374                  374
             12                      374                  374
2019         1                       374                  374
             2                       375                  375
             3                       375                  375

                          consorcio_solo_muestra_cat  unidad_id  ...  \
expensa_anio expensa_mes                                         ...
2015         1                                    48         48  ...
             2                                    51         51  ...
             3                                    51         51  ...
             4                                    56         56  ...
             5                                    56         56  ...
             6                                    61         61  ...
             7                                    66         66  ...
             8                                    68         68  ...
             9                                    70         70  ...
             10                                   70         70  ...
             11                                   71         71  ...
             12                                   74         74  ...
2016         1                                    76         76  ...
             2                                    77         77  ...
             3                                    77         77  ...
             4                                    78         78  ...
             5                                    80         80  ...
             6                                    86         86  ...
             7                                    87         87  ...
             8                                    86         86  ...
             9                                    88         88  ...
             10                                   88         88  ...
             11                                   93         93  ...
             12                                   97         97  ...
2017         1                                   102        102  ...
             2                                   108        108  ...
             3                                   110        110  ...
             4                                   110        110  ...
             5                                   112        112  ...
             6                                   114        114  ...
             7                                   123        123  ...
             8                                   174        174  ...
             9                                   367        367  ...
             10                                  368        368  ...
             11                                  368        368  ...
             12                                  368        368  ...
2018         1                                   369        369  ...
             2                                   367        367  ...
             3                                   368        368  ...
             4                                   368        368  ...
             5                                   369        369  ...
             6                                   368        368  ...
             7                                   370        370  ...

In [92]:
altosybosques.loc[(altosybosques.expensa_anio == "2015"), ["expensa_id","unidad_denominacion", "expensa_mes", "expensa_anio", "expensa_monto", "expensa_monto_total", "epensa_proporcion", "expensa_concepto", "pago_monto","pago_metodo"]].sort_values(["expensa_anio","expensa_mes"]).count()

expensa_id             742
unidad_denominacion    742
expensa_mes            742
expensa_anio           742
expensa_monto          742
expensa_monto_total    742
epensa_proporcion      742
expensa_concepto       742
pago_monto             485
pago_metodo            485
dtype: int64

In [88]:
data.pago_metodo

0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN
5                      NaN
6                 Rapipago
7                 Rapipago
8                 Rapipago
9                 Rapipago
10                Efectivo
11                Rapipago
12                Rapipago
13                Rapipago
14                Rapipago
15                Rapipago
16                Rapipago
17                Rapipago
18                Rapipago
19                Rapipago
20                Rapipago
21              Pago Facil
22                Rapipago
23                Rapipago
24                Rapipago
25              Pago Facil
26              Pago Facil
27              Pago Facil
28                Rapipago
29                Rapipago
30                Rapipago
31                Rapipago
32              Pago Facil
33                Rapipago
34              Pago Facil
35                Rapipago
36                Rapipago
37              Pago Facil
38                Rapipago
39                Rapipago
40              Pago Facil
41              Pago Facil
42              Pago Facil
43              Pago Facil
44              Pago Facil
45              Pago Facil
46              Pago Facil
47                Rapipago
48              Pago Facil
49                Rapipago
50                Rapipago
51              Pago Facil
52              Pago Facil
53              Pago Facil
54                Rapipago
55                Rapipago
56              Pago Facil
57              Pago Facil
58              Pago Facil
59                Rapipago
60              Pago Facil
61              Pago Facil
62              Pago Facil
63              Pago Facil
64              Pago Facil
65              Pago Facil
66                     NaN
67                     NaN
68                     NaN
69                     NaN
70                     NaN
71                     NaN
72                Rapipago
73                Rapipago
74                Rapipago
75                Rapipago
76                Rapipago
77                Rapipago
78                Rapipago
79                Rapipago
80                Rapipago
81        Pago Mis Cuentas
82                Rapipago
83                Rapipago
84                Rapipago
85                Rapipago
86                Rapipago
87                Rapipago
88                Rapipago
89                Rapipago
90                Rapipago
91                Rapipago
92                Rapipago
93                Rapipago
94                Rapipago
95                Rapipago
96                Rapipago
97                Rapipago
98                Rapipago
99                Rapipago
                ...
276584          Pago Facil
276585            Efectivo
276586                 NaN
276587                 NaN
276588            Efectivo
276589                 NaN
276590            Efectivo
276591                 NaN
276592                 NaN
276593                 NaN
276594            Efectivo
276595                 NaN
276596            Efectivo
276597                 NaN
276598            Efectivo
276599          Link Pagos
276600            Efectivo
276601            Efectivo
276602                 NaN
276603                 NaN
276604            Efectivo
276605            Efectivo
276606          Link Pagos
276607            Efectivo
276608                 NaN
276609                 NaN
276610                 NaN
276611            Efectivo
276612                 NaN
276613                 NaN
276614            Efectivo
276615            Rapipago
276616            Efectivo
276617                 NaN
276618            Efectivo
276619                 NaN
276620            Efectivo
276621            Efectivo
276622                 NaN
276623                 NaN
276624                 NaN
276625          Link Pagos
276626                 NaN
276627            Efectivo
276628                 NaN
276629            Efectivo
276630            Efectivo
276631            Efectivo
276632            Efectivo
276633            Efectivo
276634                 NaN
276635                 NaN
276636                 NaN
276637                 NaN
276638            Efectivo
276639            Rapipago
276640            Efectivo
276641            Efectivo
276642            Efectivo
276643            Efectivo
276644          Pago Facil
276645            Efectivo
276646                 NaN
276647            Efectivo
276648                 NaN
276649            Efectivo
276650          Link Pagos
276651            Efectivo
276652                 NaN
276653            Efectivo
276654                 NaN
276655                 NaN
276656            Efectivo
276657                 NaN
276658                 NaN
276659            Efectivo
276660            Rapipago
276661            Efectivo
276662            Rapipago
276663            Efectivo
276664                 NaN
276665            Efectivo
276666            Efectivo
276667          Pago Facil
276668                 NaN
276669                 NaN
276670                 NaN
276671                 NaN
276672                 NaN
276673                 NaN
276674                 NaN
276675                 NaN
276676                 NaN
276677                 NaN
276678                 NaN
276679                 NaN
276680                 NaN
276681                 NaN
276682            Efectivo
276683          Pago Facil
Name: pago_metodo, Length: 276684, dtype: object